const { chromium } = require('playwright');
const fs = require('fs');
const FINAL_TITLE='Sua vida financeira, em uma tela.';

async function deepest(page){const chain=[];let f=page.mainFrame();for(let i=0;i<12;i++){chain.push(f.url());const kids=f.childFrames();if(!kids.length)break;f=kids[0]}return {f,chain}}
async function waitState(f,predicate,arg,timeout=8000){await f.waitForFunction(predicate,arg,{timeout})}
async function clickNav(f,target){const b=f.locator(`.nav [data-v143-dest="${target}"]`).first();await b.waitFor({state:'visible',timeout:5000});await b.click({timeout:5000});await waitState(f,t=>window.V===t,target,5000);await f.waitForTimeout(120);return await f.evaluate(t=>({target:t,current:window.V,active:Array.from(document.querySelectorAll('.nav button.active')).map(x=>String(x.textContent||'').trim()),text:(document.getElementById('A')?.innerText||document.body.innerText||'').slice(0,5000),updateRoot:!!document.getElementById('v146UpdatesRoot'),renderCount:window.__LTS_V146_UPDATES_RENDER_COUNT||0}),target)}

async function run(browser,viewport,label){
  const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push('pageerror:'+e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});
  await page.goto('http://127.0.0.1:8772/wip35-v146-candidate.html',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(4200);
  const {f,chain}=await deepest(page);const expected=['wip35-v146-candidate.html','wip35-v142-candidate.html','wip35-v141-candidate.html','wip35-v140-candidate.html','wip35-v139-candidate.html','wip35-v138-candidate.html','wip35-v137-candidate.html','index.html'];const chainOk=expected.every((x,i)=>chain[i]&&chain[i].includes(x));
  await waitState(f,()=>window.LTS_V146_UPDATES==='single-render-updates-navigation-v1'&&window.LTS_V144_LEXICAL_BRIDGE==='v144-lexical-state-bridge-v1',null,10000);
  await f.evaluate(()=>{window.D={updates:{items:[],maintenance_checks:[],freshness:{position_as_of:'2026-08-31'},guardrail:'Itens resolvidos não reaparecem; nenhuma classificação ambígua é gravada sem confirmação.'},semantic_review:{pending_groups:0,items:[]},card_classification_review:{pending_groups:3,pending_lines:4,pending_value:2200,safe_suggestion_groups:0,category_options:['Restaurantes','Restaurantes e Lazer','Supermercado','Outros'],items:[{description_key:'sal gastronomia',merchant_name:'Sal Gastronomia',example_description:'SAL GASTRONOMIA',card_name:'Visa Aeternum',due_date:'2026-09-25',occurrences:1,total_value:933.38,suggested_category:'Restaurantes',suggestion_confidence:.99,suggestion_basis:'estabelecimento_identificado_pesquisa_publica',enrichment_attempted:true,merchant_identified:true,enrichment_confidence:.99,enrichment_evidence:'Site oficial do Sal Gastronomia identifica explicitamente o estabelecimento como restaurante em São Paulo.',taxonomy_ambiguous:true,enrichment_status:'taxonomy_review',suggestion_safe:false},{description_key:'gula gula morumbi',merchant_name:'Gula Gula',example_description:'GULA GULA MORUMBI',card_name:'Aeternum',due_date:'2026-09-10',occurrences:2,total_value:725.46,suggested_category:'Restaurantes',suggestion_confidence:.99,suggestion_basis:'estabelecimento_identificado_pesquisa_publica',enrichment_attempted:true,merchant_identified:true,enrichment_confidence:.99,enrichment_evidence:'Site oficial do Gula Gula identifica a marca como restaurante.',taxonomy_ambiguous:true,enrichment_status:'taxonomy_review',suggestion_safe:false},{description_key:'zigpay exemplo',merchant_name:'ZigPay',example_description:'ZIGPAY*EXEMPLO',card_name:'Aeternum',due_date:'2026-09-10',occurrences:1,total_value:541.16,suggested_category:null,suggestion_confidence:0,suggestion_basis:'pesquisa_publica_realizada_inconclusiva',enrichment_attempted:true,merchant_identified:true,enrichment_confidence:.94,enrichment_evidence:'Intermediador de pagamentos identificado; o estabelecimento final não está provado.',taxonomy_ambiguous:false,enrichment_status:'payment_intermediary_needs_context',suggestion_safe:false}]},dashboard_cockpit:{version:'v146-smoke',as_of:'2026-08-31',status:'attention',liquidity:{through_d3:100000,bank_cash:50000,d0:25000,d3_vested:25000,fgts_d30:17509.05},planning_audited:{management_point_date:'2027-01-08',fgts_request_by:'2026-12-09',worst_after_brl:11262.25},cards:{open_cycles_total:1000,closed_or_due_total:0,next_due:{}},work:{actionable_count:0,top_actions:[]},horizons:[],future_liquidity:[]},flow:{days:[],events:[]},card_history:{units:[]},duplicate_quality_gate:{},card_operating:{},expenses:{},wealth:{},planning:{}};window.V='Atualizações';window.renderNav?.();window.render()});await page.waitForTimeout(500);
  const content=await f.evaluate(()=>{const get=k=>document.querySelector(`[data-v146-key="${k}"]`);const rowState=k=>{const r=get(k),sel=r?.querySelector('.cardcat');return {exists:!!r,text:r?.innerText||'',selected:sel?.value||'',save:!!r?.querySelector('.cardclass-save'),newcat:!!r?.querySelector('.newcatbtn'),safe:!!r?.querySelector('.safe121-pick')}};return {marker:window.LTS_V146_UPDATES||null,status:window.__LTS_V146_UPDATES_STATUS||null,root:!!document.getElementById('v146UpdatesRoot'),sal:rowState('sal gastronomia'),gula:rowState('gula gula morumbi'),zig:rowState('zigpay exemplo'),width:document.documentElement.clientWidth,scroll:Math.max(document.documentElement.scrollWidth,document.body?.scrollWidth||0)}});
  const contentOk=content.marker==='single-render-updates-navigation-v1'&&content.status?.permanent_polling===false&&content.status?.dom_reparenting===false&&content.root&&content.sal.exists&&content.sal.selected==='Restaurantes'&&content.sal.text.includes('99% sugestão')&&content.sal.text.includes('99% identificação')&&content.sal.text.includes('Pesquisa pública')&&!content.sal.safe&&content.gula.selected==='Restaurantes'&&content.gula.text.includes('99% sugestão')&&!content.gula.safe&&content.zig.selected===''&&content.zig.text.includes('Intermediador')&&content.sal.save&&content.sal.newcat;
  const transitions=[];for(let i=0;i<10;i++){const before=await f.evaluate(()=>window.__LTS_V146_UPDATES_RENDER_COUNT||0);const flow=await clickNav(f,'Fluxo Diário');await page.waitForTimeout(450);const afterFlow=await f.evaluate(()=>window.__LTS_V146_UPDATES_RENDER_COUNT||0);transitions.push({cycle:i,step:'Fluxo Diário',...flow,stableNoUpdateRender:afterFlow===before,contentOk:flow.text.includes('Fluxo Diário')&&!flow.updateRoot});const dash=await clickNav(f,'Dashboard');await page.waitForTimeout(350);const dashTitle=await f.evaluate(()=>document.querySelector('.v143-head h1')?.textContent||'');transitions.push({cycle:i,step:'Dashboard',...dash,title:dashTitle,contentOk:dashTitle===FINAL_TITLE&&!dash.updateRoot});const upd=await clickNav(f,'Atualizações');await page.waitForTimeout(200);const salVisible=await f.evaluate(()=>!!document.querySelector('[data-v146-key="sal gastronomia"]'));transitions.push({cycle:i,step:'Atualizações',...upd,salVisible,contentOk:upd.updateRoot&&salVisible})}
  const navigationOk=transitions.every(x=>x.current===x.step&&x.active.some(a=>a===x.step)&&x.contentOk&&(x.step!=='Fluxo Diário'||x.stableNoUpdateRender));
  await clickNav(f,'Dashboard');const titles=[];for(let i=0;i<15;i++){await page.waitForTimeout(100);titles.push(await f.evaluate(()=>document.querySelector('.v143-head h1')?.textContent||''))}const titleSet=[...new Set(titles)];const dimensions=await f.evaluate(()=>({width:document.documentElement.clientWidth,scroll:Math.max(document.documentElement.scrollWidth,document.body?.scrollWidth||0)}));const pass=chainOk&&contentOk&&navigationOk&&titleSet.length===1&&titleSet[0]===FINAL_TITLE&&content.scroll-content.width<=2&&dimensions.scroll-dimensions.width<=2&&errors.length===0;await page.close();return {label,viewport,pass,chain,chainOk,content,contentOk,navigationOk,transitions,titleSet,dimensions,errors}
}
(async()=>{const browser=await chromium.launch({headless:true});const desktop=await run(browser,{width:1440,height:1000},'desktop');const mobile=await run(browser,{width:390,height:844},'mobile-390x844');await browser.close();const result={pass:desktop.pass&&mobile.pass,desktop,mobile,importantLimit:'Synthetic browser smoke proves assisted classification rendering and repeated real nav-button transitions without v144 polling/DOM reparenting. It is unauthenticated, does not confirm classifications, and executes no financial writes.'};fs.writeFileSync('v146-updates-navigation-smoke-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.pass)process.exit(1)})().catch(e=>{console.error(e);process.exit(1)});
