const { chromium } = require('playwright');
const fs = require('fs');
const V147='guided-document-association-v1';
const V148='classification-save-refresh-self-heal-visible-version-v3';
const V149='document-interpretation-review-v1';
async function deepest(page){const chain=[];let f=page.mainFrame();for(let i=0;i<14;i++){chain.push(f.url());const kids=f.childFrames();if(!kids.length)break;f=kids[0]}return {f,chain}}
async function run(viewport,label){let stage='launch',f=null,chain=[];const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push('pageerror:'+e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});try{
  stage='load';await page.goto('http://127.0.0.1:8775/wip35-v149-candidate.html',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(5200);({f,chain}=await deepest(page));
  const expected=['wip35-v149-candidate.html','wip35-v147-candidate.html','wip35-v146-candidate.html','wip35-v142-candidate.html','wip35-v141-candidate.html','wip35-v140-candidate.html','wip35-v139-candidate.html','wip35-v138-candidate.html','wip35-v137-candidate.html','index.html'];const chainOk=expected.every((x,i)=>chain[i]&&chain[i].includes(x));if(!chainOk)throw Error('candidate chain mismatch: '+JSON.stringify(chain));
  stage='markers';await f.waitForFunction(m=>window.LTS_V147_DOCUMENT_ASSOCIATION===m,V147,{timeout:10000});await f.waitForFunction(m=>window.LTS_V148_CLASSIFICATION_LIFECYCLE===m,V148,{timeout:10000});await f.waitForFunction(m=>window.LTS_V149_DOCUMENT_INTERPRETATION_REVIEW===m,V149,{timeout:10000});
  stage='seed';await f.evaluate(()=>{window.D={input:{queue:[{id:'doc1',original_name:'posicao-cipo.pdf',status:'needs_review',interpretation:{task_context:{document_association:{version:'guided-document-association-v1',document_type:'financing_statement',entity_type:'financial_commitment',entity_label:'CIPÓ 396',as_of_date:'2026-08-31',provided_by_user:true,review_required:true}},extracted_fields:{outstanding_balance:{value:'6502.70',confidence:0.92,page:2},statement_date:{value:'2026-08-31',confidence:0.99,page:1}}}},{id:'doc2',original_name:'foto-documento.jpg',status:'needs_review',interpretation:{extracted_fields:{balance:{value:'17509.05',confidence:0.71,page:1}}}}]},wealth:{accounts:[]},flow:{accounts:[]},card_operating:{open_cycles:[]},card_history:{units:[],cards:[]},commitments:{commitments:[]},documentary_commitments:{items:[]},updates:{items:[],maintenance_checks:[]},card_classification_review:{pending_groups:0,items:[],category_options:[]},semantic_review:{pending_groups:0,items:[]}};window.V='Entradas';window.renderNav?.();window.render()});
  stage='panel';await f.waitForSelector('#v147DocAssociation',{state:'attached',timeout:6000});await f.waitForSelector('#v149DocumentReview',{state:'attached',timeout:6000});await f.waitForTimeout(300);const text=await f.locator('#v149DocumentReview').innerText();for(const x of ['CIPÓ 396','6502.70','2026-08-31','17509.05','needs_review','associação explícita','filename','revisão manual'])if(!text.toLowerCase().includes(x.toLowerCase()))throw Error('review panel missing '+x+': '+text);
  stage='guardrails';const status=await f.evaluate(()=>window.__LTS_V149_DOCUMENT_REVIEW_STATUS);if(!status||status.financial_writer_changed!==false||status.rpc_calls!==0||status.filename_inference!==false||status.manual_review_required!==true||status.permanent_polling!==false)throw Error('v149 guardrails invalid: '+JSON.stringify(status));const s148=await f.evaluate(()=>window.__LTS_V148_CLASSIFICATION_STATUS);if(!s148||s148.financial_rules_changed!==false||s148.classification_inference!==false)throw Error('v148 lifecycle not preserved: '+JSON.stringify(s148));
  stage='version';await page.waitForTimeout(8000);const visible=await page.evaluate(()=>({top:window.__LTS_V149_VISIBLE_VERSION_STATUS,labels:Array.from(document.querySelectorAll('#badge,.brand small,.footer'),x=>x.textContent||'')}));const deepVisible=await f.evaluate(()=>({status:window.__LTS_V149_VISIBLE_VERSION_STATUS,labels:Array.from(document.querySelectorAll('#badge,.brand small,.footer'),x=>x.textContent||'')}));const labels=[...(visible.labels||[]),...(deepVisible.labels||[])];if(!visible.top||visible.top.older_version_visible||deepVisible.status?.older_version_visible||labels.some(x=>/v14[0-8]\b/i.test(x))||!labels.some(x=>/v149\b/i.test(x)))throw Error('visible version ownership failed: '+JSON.stringify({visible,deepVisible}));
  stage='errors';if(errors.some(x=>/v149|document interpretation|mutation|maximum call stack/i.test(x)))throw Error('relevant browser errors: '+JSON.stringify(errors));return {label,viewport,chain,chainOk,status,s148,text,visible,deepVisible,errors};
}catch(err){let snapshot=null;try{snapshot=await f?.evaluate(()=>({V:window.V,status:window.__LTS_V149_DOCUMENT_REVIEW_STATUS,visible:window.__LTS_V149_VISIBLE_VERSION_STATUS,panel:document.getElementById('v149DocumentReview')?.innerText||null,body:(document.body?.innerText||'').slice(0,5000)}))}catch(e){snapshot={snapshot_error:String(e?.stack||e)}}const fail={version:'v149-document-interpretation-review',pass:false,label,viewport,stage,chain,snapshot,errors,fatal:String(err?.stack||err)};try{fs.writeFileSync('v149-document-interpretation-review-smoke-result.json',JSON.stringify(fail,null,2))}catch(_){}throw err}finally{await browser.close()}}
(async()=>{const desktop=await run({width:1440,height:900},'desktop');const mobile=await run({width:390,height:844},'mobile');const out={version:'v149-document-interpretation-review',marker:V149,desktop,mobile,pass:true};fs.writeFileSync('v149-document-interpretation-review-smoke-result.json',JSON.stringify(out,null,2));console.log('v149_document_interpretation_review_smoke=PASS')})().catch(err=>{console.error(err);process.exit(1)});
