const { chromium } = require('playwright');
const fs = require('fs');
const stage=(label,msg)=>console.log(`[v151-smoke] ${label} :: ${msg}`);
const watchdog=setTimeout(()=>{console.error('[v151-smoke] WATCHDOG_TIMEOUT :: gate exceeded 60s');process.exit(124)},60000);

async function deepest(page){let f=page.mainFrame(),chain=[];for(let i=0;i<18;i++){chain.push(f.url());const kids=f.childFrames();if(!kids.length)break;f=kids[0]}return {f,chain}}
const has=(t,n)=>String(t||'').toLocaleLowerCase('pt-BR').includes(String(n||'').toLocaleLowerCase('pt-BR'));
function data(){return {
  dashboard_cockpit:{version:'v151-smoke',as_of:'2026-09-03',liquidity:{through_d3:75133.58,bank_cash:19294.43,d0:42929.50,d3_vested:12909.65,fgts_d30:22432.31,accounts:[{institution:'Itaú',balance:15402.31},{institution:'Bradesco',balance:2931.96},{institution:'C6',balance:960.16}]},cards:{open_cycles_total:33328.63,closed_or_due_total:960.16,next_due:{due_date:'2026-09-08',amount:960.16,card_name:'C6 Carbon'}},work:{actionable_count:20,classification_groups:3,top_actions:[{title:'Revisar documento pendente',description:'Documento aguardando revisão'}]},planning_audited:{management_point_date:'2026-12-30',fgts_request_by:'2026-11-30',coverage_amount_brl:22432.31,worst_before_brl:-25782.39,worst_after_brl:-3350.08,first_uncovered_gap_date:'2027-01-30',covers_horizon:false,fgts_future_accrual_estimated:false},horizons:[{id:'30d',date:'2026-10-03',current_liquidity_balance:33219.79},{id:'90d',date:'2026-12-02',current_liquidity_balance:18560.47},{id:'year_end',date:'2026-12-31',current_liquidity_balance:4200.11}],wealth:{assets_central:5462642.63,known_debt_total:1890398.31,net_worth_central:3572244.32},expenses:{current_month:{spend:68000},previous_month:{spend:62000}}},
  wealth_executive:{summary:{assets_central:5462642.63,known_debt_total:1890398.31,net_worth_central:3572244.32},assets:{cipo_396:{market_central:5200000},volvo_xc40:{market_central:170000}}},
  updates:{items:[],maintenance_checks:[],freshness:{position_as_of:'2026-09-03'}},semantic_review:{pending_groups:0,items:[]},
  card_classification_review:{pending_groups:3,pending_lines:3,pending_value:1610.41,category_options:['Restaurantes','Moradia','Saúde'],items:[{description_key:'lavandex lavanderia lt',example_description:'LAVANDEX LAVANDERIA LT',total_value:380,merchant_name:'Lavandex Lavanderia LTDA',merchant_identified:true,enrichment_status:'identified_needs_taxonomy',enrichment_evidence:'CNAE Lavanderias',suggested_category:null},{description_key:'dufry lojas francas',example_description:'DUFRY LOJAS FRANCAS',total_value:297.64,merchant_name:'Dufry Lojas Francas',merchant_identified:true,enrichment_status:'identified_needs_context',enrichment_evidence:'loja franca duty free',suggested_category:null},{description_key:'sal gastronomia',example_description:'SAL GASTRONOMIA',total_value:933.38,merchant_name:'Sal Gastronomia',merchant_identified:true,enrichment_status:'taxonomy_review',enrichment_evidence:'restaurante',suggested_category:'Restaurantes',suggestion_confidence:.99}]},
  flow:{days:[],events:[]},card_history:{units:[]},duplicate_quality_gate:{},card_operating:{},expenses:{},wealth:{},planning:{}}
}
function matrix(){return {version:'expense-context-nature-matrix-v1',summary:{rows:629,total:722126.87,unassigned_rows:483,unassigned_total:360902.80},contexts:[{name:'Casa',rows:39,total:201241.45,categories:[{category:'Moradia',rows:8,total:29719.87}]},{name:'Benjamin',rows:65,total:64496.10,categories:[{category:'Educação',rows:18,total:45934.53}]}],categories:[{name:'Moradia',rows:8,total:29719.87,contexts:[{context:'Casa',rows:8,total:29719.87}]}],unassigned_states:[{state:'documentary_detail_not_recovered',rows:16,total:186252.10},{state:'detail_available_system_review',rows:412,total:165493.93},{state:'classification_and_context_pending',rows:55,total:9156.77}],unassigned_categories:[]}}
function tx(){return [{date:'2028-04-12',description:'MASTERCARD FUTURO',account:'Itaú',direction:'saida',amount:1200,category:'Cartão',counterparty:'Mastercard',center_cost:'Lucas',source:'commitments',source_ref:'mc-future'},{date:'2013-11-01',description:'MASTERCARD HISTÓRICO',account:'Itaú',direction:'saida',amount:500,category:'Cartão',counterparty:'Mastercard',center_cost:'Lucas',source:'ledger',source_ref:'mc-2013'}]}
async function view(f,v){await f.evaluate(x=>{window.V=x;window.renderNav?.();window.render();window.__LTS_V150_AFTER_RENDER?.();window.__LTS_V151_AFTER_RENDER?.();window.__LTS_V151_LEDGER_SEARCH_AFTER_RENDER?.();window.__LTS_V151_WRAPPER_REPAINT?.()},v)}
async function forceShell(f){await f.evaluate(()=>{for(const [sel,disp] of [['.hdr','block'],['.hdrin','block'],['.nav','flex'],['#A','block'],['.wrap','block']]){const el=document.querySelector(sel);if(el){el.classList.remove('hidden');el.style.setProperty('display',disp,'important');el.style.setProperty('visibility','visible','important')}}})}
async function run(browser,viewport,label){
  stage(label,'page-open');
  const page=await browser.newPage({viewport}),errors=[];page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.goto('http://127.0.0.1:8777/wip35-v151-candidate.html',{waitUntil:'domcontentloaded',timeout:30000});stage(label,'domcontentloaded');await page.waitForTimeout(4300);stage(label,'settled');
  const {f,chain}=await deepest(page);stage(label,'deepest-frame');if(!chain[0].includes('wip35-v151-candidate.html')||!chain.some(x=>x.includes('wip35-v150-candidate.html')))throw Error(label+' invalid chain '+JSON.stringify(chain));
  const D=data(),M=matrix(),T=tx();
  await f.evaluate(({D,M,T})=>{window.D=D;window.__V151_RPC_CALLS=[];if(!window.S||typeof window.S!=='object')throw Error('Supabase client missing');window.S.rpc=async(name,args)=>{window.__V151_RPC_CALLS.push({name,args});if(name==='lts_browser_product_v1')return {data:{mvp:D},error:null};if(name==='lts_browser_expense_context_nature_v1')return {data:M,error:null};if(name==='lts_browser_expense_drilldown_v1')return {data:{rows:[]},error:null};if(name==='lts_browser_transactions_v1'){const q=String(args?.p_query||'').toLowerCase();const rows=q.includes('mastercard')?T:[];return {data:{ok:true,total:rows.length,limit:args?.p_limit||200,offset:args?.p_offset||0,rows},error:null}}if(name==='lts_browser_flow_v4')return {data:{flow:{historical:{events:[]},current_future:{events:[]}}},error:null};return {data:{ok:true},error:null}};window.V='Dashboard';window.renderNav?.();window.render()}, {D,M,T});stage(label,'rpc-mock-and-render');
  await f.waitForFunction(()=>window.LTS_V151_COCKPIT==='dashboard-updates-cockpit-v1'&&window.LTS_V151_LEDGER_SEARCH==='ledger-search-export-v1'&&typeof window.__LTS_V151_WRAPPER_REPAINT==='function',null,{timeout:12000});stage(label,'layers-ready');
  await f.evaluate(D=>{window.D=D;window.__V150_EXP=null;window.dashboard=window.__LTS_V151_DASHBOARD_FN;window.__v143Dashboard=window.__LTS_V151_DASHBOARD_FN},D);await view(f,'Dashboard');stage(label,'dashboard-view');await forceShell(f);await page.waitForTimeout(300);
  let text=await f.locator('body').innerText();for(const needle of ['Sua vida financeira, em uma tela.','Disponível D+3','FGTS','22.432,31','Liquidez','Evolução do caixa','Patrimônio e posição financeira','O que exige minha atenção','-R$ 3.350,08'])if(!has(text,needle))throw Error(label+' dashboard missing '+needle);
  if(has(text,'32.309,05')||has(text,'11.262,25'))throw Error(label+' stale projected FGTS planning visible');stage(label,'dashboard-validated');
  const wrapper=await f.evaluate(()=>window.parent?.parent?.parent?.__LTS_V151_WRAPPER_STATUS||window.__LTS_V151_WRAPPER_STATUS||null).catch(()=>null);
  await view(f,'Atualizações');stage(label,'updates-view');await f.waitForSelector('#v151LedgerSearch',{timeout:7000});await f.waitForSelector('#v151UpdateSummary',{timeout:7000});stage(label,'ledger-mounted');
  const input=f.locator('#v151LedgerTerm');await input.fill('Mastercard');stage(label,'ledger-query-filled');await f.waitForFunction(()=>window.__LTS_V151_LEDGER_SEARCH_STATUS?.pass===true&&window.__LTS_V151_LEDGER_SEARCH_STATUS?.query==='Mastercard',null,{timeout:7000});stage(label,'ledger-query-ready');text=await f.locator('#v151LedgerSearch').innerText();for(const needle of ['Encontrar lançamentos','2 lançamento','MASTERCARD FUTURO','MASTERCARD HISTÓRICO','Exportar para Excel'])if(!has(text,needle))throw Error(label+' ledger search missing '+needle+' '+text);
  const searchState=await f.evaluate(()=>({status:window.__LTS_V151_LEDGER_SEARCH_STATUS,calls:window.__V151_RPC_CALLS,observer:!!window.__LTS_V151_DECORATION_OBSERVER}));if(searchState.status?.from!=='2013-10-10'||searchState.status?.to!==null||searchState.status?.server_side!==true||searchState.status?.writer_added!==false)throw Error('ledger guardrail '+JSON.stringify(searchState.status));const txCalls=searchState.calls.filter(x=>x.name==='lts_browser_transactions_v1');if(!txCalls.length)throw Error('transactions RPC not called');if(searchState.calls.some(x=>x.name==='lts_browser_flow_v4'))throw Error('legacy flow RPC used by ledger search');if(searchState.observer)throw Error('permanent v151 decoration observer active');stage(label,'ledger-validated');
  await view(f,'Despesas');stage(label,'expenses-view');await f.waitForSelector('#v151ExpenseState',{timeout:7000});stage(label,'expenses-mounted');text=await f.locator('body').innerText();for(const needle of ['Histórico sem detalhe recuperado','LTS ainda investigando','Realmente para classificar/contextualizar','Casa é contexto','Moradia é natureza'])if(!has(text,needle))throw Error(label+' expenses missing '+needle);
  const st=await f.evaluate(()=>({s:window.__LTS_V151_STATUS,calls:window.__V151_RPC_CALLS||[]}));if(st.s?.financial_writer_changed!==false||st.s?.classification_inference!==false||st.s?.classification_writer_added!==false||st.s?.navigation_owner_changed!==false||st.s?.permanent_polling!==false)throw Error('guardrails invalid '+JSON.stringify(st.s));const forbidden=st.calls.map(x=>x.name).filter(x=>/apply|approve|write|feedback/i.test(x));if(forbidden.length)throw Error('writer RPC '+forbidden.join(','));if(errors.length)throw Error('browser errors '+JSON.stringify(errors));stage(label,'guardrails-validated');await page.close();stage(label,'complete');return {label,viewport,pass:true,chain,rpc:st.calls.map(x=>x.name),ledger:searchState.status,wrapper}
}
(async()=>{const browser=await chromium.launch({headless:true});try{const results=[await run(browser,{width:1440,height:900},'desktop'),await run(browser,{width:390,height:844},'mobile')];const out={pass:true,version:'v151-dashboard-updates-ledger-search',results};fs.writeFileSync('v151-dashboard-updates-smoke-result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}catch(e){const out={pass:false,error:String(e?.stack||e)};fs.writeFileSync('v151-dashboard-updates-smoke-result.json',JSON.stringify(out,null,2));console.error(out.error);process.exitCode=1}finally{clearTimeout(watchdog);await browser.close()}})();
