'use strict';

const {chromium}=require('playwright');
const fs=require('node:fs');
const {BASE,cockpit,wealth:baseWealth,product:baseProduct,expensePayload,semantic}=require('./lts_v165_executive_ux_gate.js');

const session={access_token:'fixture-token',refresh_token:'fixture-refresh',expires_at:4102444800,user:{id:'fixture-user'}};
const brl=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);

function productFixture(){const x=baseProduct();x.card_operating=x.card_operating||{open_cycles:[],closed_or_due:[],contracted_installment_floor_months:[],classification_review:{}};return x}
function managementGroups(){return [
  {name:'Financiamentos',total:230000,rows:12,subgroups:[{name:'Financiamento imobiliário · Casa',total:207000,rows:10},{name:'Financiamento imobiliário · CIPÓ 396',total:20000,rows:1},{name:'Financiamento de veículo',total:3000,rows:1}],source_categories:[{name:'Financiamento Imobiliário',total:227000,rows:11},{name:'Financiamento veículo',total:3000,rows:1}]},
  {name:'Empréstimos',total:121000,rows:21,subgroups:[{name:'Empréstimo · Itaú',total:72000,rows:10},{name:'Consignado · Coopharma',total:49000,rows:11}],source_categories:[{name:'Empréstimos',total:72000,rows:10},{name:'Compromissos Financeiros',total:49000,rows:11}]},
  {name:'Educação',total:71000,rows:41,subgroups:[{name:'Educação · benjamin',total:56000,rows:25},{name:'Educação · lucas',total:8500,rows:12},{name:'Educação · não atribuído',total:6500,rows:4}],source_categories:[{name:'Educação',total:71000,rows:41}]},
  {name:'Saúde',total:63000,rows:94,subgroups:[{name:'Saúde',total:63000,rows:94}],source_categories:[{name:'Saúde',total:63000,rows:94}]},
  {name:'Obra e reforma · O Parque / CIPÓ 396',total:34340,rows:18,subgroups:[{name:'Cortinas E Persianas',total:17500,rows:3},{name:'Móveis',total:7500,rows:4},{name:'Eletrodomésticos',total:6700,rows:3},{name:'Mão de obra e serviços',total:500,rows:1},{name:'Material Obra',total:140,rows:1}],source_categories:[{name:'Cortinas E Persianas - O Parque',total:17500,rows:3},{name:'Móveis - O Parque',total:7500,rows:4}]},
  ...['Moradia','Vestuário','Restaurantes','Benjamin','Impostos do Imóvel','Rafiki','Energia','Família','Farmácia','Presentes','Mercado'].map((name,index)=>({name,total:30000-index*1500,rows:10,subgroups:[{name,total:30000-index*1500,rows:10}],source_categories:[{name,total:30000-index*1500,rows:10}]}))
]}
function expenseFixture(from,to){const data=expensePayload(from,to);data.management_groups=managementGroups();data.management_group_audit={financing_brl:230000,loans_brl:121000,works_brl:34340,education_brl:71000,financing_definition:'Somente parcelas classificadas como financiamento imobiliário ou de veículo.',works_definition:'Itens de O Parque/CIPÓ 396, excluindo as parcelas de financiamento.'};data.coverage_disclosure={total:294839.37,rows:26,label:'Faturas históricas sem compras individualizadas',guardrail:'O total econômico foi preservado fora dos grupos gerenciais; estabelecimentos e categorias não são inventados.'};data.rankings={categories:[{name:'Cartão — detalhe histórico não recuperado',total:294839.37},{name:'Financiamento Imobiliário',total:230000},{name:'Educação',total:71000}],centers:[{name:'Benjamin',total:100000}]};return data}
function wealthFixture(){return {
  ...baseWealth,version:'wealth-detail-v5-v170-morgan-reconciled',as_of:'2030-06-15',
  wealth:{...baseWealth.wealth,liquidity:{bank_cash:48000,d0:12000,fgts_contingency:25000},summary:{...baseWealth.wealth.summary,known_debt_total:450000},assets:{cipo_396:{market_central:1700000,documentary_debt:400000,equity_central:1300000,historical_purchase_plus_reform:900000},volvo_xc40:{market_central:120000,documented_financed_balance:50000,equity_central:70000}}},
  wealth_v167:{net_worth_central_including_pensions:1600000,assets_central_including_pensions:2050000},
  pensions:{total_gross_brl:150000,positions:[{name:'Organon Multiprev',as_of:'2030-06-14',gross_balance_brl:100000,profile:'Moderado'},{name:'Novartis Previ Plano D',as_of:'2030-05-31',gross_balance_brl:50000,profile:'Moderado'}]},
  rsu_summary:{as_of:'2026-09-17',vested_shares_brl:13012.45,brokerage_cash_brl:2900.98,available_total_brl:15913.44,future_regular_brl:321250,future_cash_net_brl:78750,future_considered_total_brl:400000},
  morgan_statement:{institution:'Morgan Stanley',as_of:'2026-09-17',source_label:'Morgan Stanley · carteira exibida em 17/09/2026',gross_total_brl:1745784.67,available_total_brl:15913.44,unavailable_gross_brl:1729871.23,available_components:{vested_shares_brl:13012.45,brokerage_cash_brl:2900.98,rounding_delta_brl:.01},future_components:{regular_rsu_gross_brl:1142654.04,cash_rsu_gross_brl:587217.19,cash_rsu_after_reserve_brl:411052.03,cash_rsu_reserve_brl:176165.16,future_after_reserve_brl:1553706.07},considered_total_after_reserve_brl:1569619.51,reserve_rate:.3,quantities:{vested_shares:184.954,future_regular_rsu:16080,future_cash_rsu:8310},planning_schedule_reconciliation:{regular_delta_brl:7594.05,cash_delta_brl:10314.72,status:'statement_and_assumption_model_kept_separate'}},
  financing:{summary:{commitments:[{id:'cipo_396',current_documentary_debt_balance:400000,remaining_scheduled_outflow_current_terms:900000,remaining_events:300},{id:'volvo',current_documentary_debt_balance:50000,remaining_scheduled_outflow_current_terms:76000,remaining_events:38},{id:'coopharma',current_documentary_debt_balance:null,remaining_scheduled_outflow_current_terms:31157.14,remaining_events:7},{id:'pai_mae',current_documentary_debt_balance:null,remaining_scheduled_outflow_current_terms:80000,remaining_events:10}]},documentary:{items:[]}},
  cipo_detail:{components:[],current_payoff_brl:400000,contractual_outflow_current_terms_brl:900000,historical_purchase_plus_reform_brl:900000}
}}
function flowFixture(){
  const current=(date,bank,base,after,fgts)=>({date,Consolidado:{bank_balance:bank,economic_net:0},'Itaú':{balance:bank},Bradesco:{balance:0},C6:{balance:0},fix86_columns:{saldo_anterior:bank,saldo_final:bank,liq_d0_1_recurso:12000,saldo_apos_d0_1:base,rsus_vested:15913.44,morgan_available_total_brl:15913.44,saldo_apos_rsu:after,disponivel_total:after,posicao_curto_prazo:after,fgts:25000,saldo_apos_fgts:fgts,rsus_futuras:400000,cash_awards_futuros:78750,posicao_economica_total:fgts+400000+78750}});
  const proof=(entries,exits,internal)=>({version:'tracked-bank-cash-arithmetic-v1',operating_entries_brl:entries,operating_exits_brl:exits,internal_transfer_net_brl:internal,tracked_bank_net_brl:entries-exits+internal,arithmetic_gap_brl:0,balanced:true});
  return {ok:true,flow:{from:'2030-06-10',to:'2031-12-31',available_year_from:2013,available_year_to:2041,version:'daily-flow-browser-v12-v170-auditable-balances',historical_relative_balance_contract:{version:'historical-tracked-bank-ledger-v2',opening_basis_date:'2013-10-09',opening_basis_brl:0},historical_cash_arithmetic_contract:{version:'tracked-bank-cash-arithmetic-v1'},historical_cash_arithmetic_audit:{version:'tracked-bank-cash-audit-v1',day_count:2,balanced_days:2,mismatch_days:0,max_abs_gap_brl:0,status:'balanced'},historical:{days:[
    {date:'2030-06-13',historical:true,Consolidado:{bank_balance:800,economic_net:0,balance_certified:false,balance_basis:'relative_tracked_bank_ledger'},'Itaú':{balance:800,net:300,balance_certified:false,balance_basis:'relative_tracked_bank_ledger'},Bradesco:{balance:0,net:0},C6:{balance:0,net:0},fix86_columns:{saldo_anterior_operacional:500,saldo_final_operacional:800},summary:{entries:0,exits:0,net:0},v170_cash_arithmetic:proof(0,0,300)},
    {date:'2030-06-14',historical:true,Consolidado:{bank_balance:1000,economic_net:200,balance_certified:false,balance_basis:'relative_tracked_bank_ledger'},'Itaú':{balance:1000,net:200,balance_certified:false,balance_basis:'relative_tracked_bank_ledger'},Bradesco:{balance:0,net:0},C6:{balance:0,net:0},fix86_columns:{saldo_anterior_operacional:800,saldo_final_operacional:1000},summary:{entries:200,exits:0,net:200},v170_cash_arithmetic:proof(200,0,0)}
  ],events:[
    {event_date:'2030-06-13',description:'Resgate de recurso próprio',account:'Itaú',signed_amount:300,source:'internal_transfer',source_ref:'fixture:internal-transfer',confidence:'documented_current_internal_transfer',internal_transfer:true},
    {event_date:'2030-06-14',description:'Entrada histórica recuperada',account:'Itaú',signed_amount:200,source:'historical',source_ref:'fixture:historical',internal_transfer:false}
  ]},current_future:{days:[current('2030-06-15',48000,60000,75913.44,100913.44),current('2030-12-31',17000,-7000,8913.44,33913.44),current('2031-12-31',12000,-12000,3913.44,28913.44)],events:[]},morgan_available_contract:{statement_available_total_brl:15913.44,label:'Morgan disponível'}}};
}
function contextFixture(){return {contexts:[{name:'Benjamin',total:56000,categories:[{name:'Educação',total:56000}]},{name:'Lucas',total:8500,categories:[{name:'Educação',total:8500}]}]}}

async function frameReady(page,label){for(let i=0;i<260;i++){const frame=page.frames().find(f=>{try{return new URL(f.url()).pathname.endsWith('/index.html')}catch{return false}});if(frame&&await frame.evaluate(()=>Boolean(window.__LTS_V170_V169_REVIEW?.installed&&document.querySelector('.v168-dashboard'))).catch(()=>false))return frame;await page.waitForTimeout(100)}await page.screenshot({path:`v170-${label}-failure.png`,fullPage:true});throw Error(label+': V170 frame not ready')}

async function run(browser,viewport,label){
  const context=await browser.newContext({viewport});
  await context.addInitScript(fixed=>{const NativeDate=Date,fixedMs=NativeDate.parse(fixed);class FixedDate extends NativeDate{constructor(...args){super(...(args.length?args:[fixedMs]))}static now(){return fixedMs}}window.Date=FixedDate},'2030-06-15T12:00:00Z');
  await context.addInitScript(value=>localStorage.setItem('lts_supabase_session_v1',JSON.stringify(value)),session);
  const page=await context.newPage();page.setDefaultTimeout(26000);const errors=[],consoleErrors=[],requested=[],flowCalls=[],awardMutations=[];
  page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('dialog',d=>d.accept());
  await page.route('https://tadhkamnwtsbdozwkyut.supabase.co/**',async route=>{
    const req=route.request(),name=new URL(req.url()).pathname.split('/').pop();requested.push(name);
    let args={};try{args=JSON.parse(req.postData()||'{}')}catch{}
    let body={ok:true};
    if(name==='token')body=session;
    else if(name==='lts_browser_product_v1')body={ok:true,mvp:productFixture()};
    else if(name==='lts_browser_dashboard_cockpit_v1')body=cockpit;
    else if(name==='lts_browser_flow_v12'){flowCalls.push(args);body=flowFixture()}
    else if(name==='lts_browser_expense_executive_v5'||name==='lts_browser_expense_executive_v3')body=expenseFixture(args.p_from||'2030-01-01',args.p_to||'2030-06-15');
    else if(name==='lts_browser_expense_context_lens_v1')body=contextFixture();
    else if(name==='lts_browser_expense_context_nature_v1')body={contexts:[],natures:[],summary:{}};
    else if(name==='lts_browser_wealth_detail_v4'||name==='lts_browser_wealth_detail_v2')body=wealthFixture();
    else if(name==='lts_browser_recurring_future_gap_audit_v5')body={horizon_checks:[],items:[]};
    else if(name==='lts_browser_open_finance_status_v1')body={status:'not_connected'};
    else if(name==='lts_browser_save_all_award_assumptions_v1'){
      awardMutations.push(args);body={ok:true,award_count:10,unit_price_usd:args.p_unit_price_usd,fx_rate:args.p_fx_rate};
    }else if(name==='lts_browser_monthly_balance_v1')body={version:'monthly-balance-v1',months:[],totals:{},monthly_totals:[],revenue_groups:[],extraordinary_groups:[],expense_groups:[],coverage:{}};
    await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
  });
  await page.goto(`${BASE}/wip35-v170-candidate.html`,{waitUntil:'domcontentloaded',timeout:20000});const frame=await frameReady(page,label),brand=frame.locator('.brand small');const brandVersion=await brand.evaluate(node=>getComputedStyle(node,'::before').content),legacyBrandVisible=await brand.locator('b').isVisible().catch(()=>false);const scopeVersion=await page.locator('#scope').evaluate(node=>getComputedStyle(node,'::before').content);if(!brandVersion.includes('V170')||!scopeVersion.includes('V170')||legacyBrandVisible)throw Error(`${label}: visible homologation version is not exclusively V170`);
  try{
    await frame.waitForFunction(()=>window.__LTS_V168_STATE?.dashboard?.pending===0&&window.__LTS_V168_STATE?.dashboard?.data?.expense?.management_groups);
  }catch(error){
    const diagnostic=await frame.evaluate(()=>({route:window.V,dashboard:window.__LTS_V168_STATE?.dashboard,rpcCalls:window.__LTS_V170_V169_REVIEW?.rpcCalls})).catch(()=>null);
    console.error(JSON.stringify({label,requested,errors,consoleErrors,diagnostic},null,2));
    throw error;
  }
  let text=semantic(await frame.locator('.v168-dashboard').innerText());for(const phrase of ['top 15','educação · benjamin','educação · lucas','obra e reforma · o parque / cipó 396','faturas históricas sem compras individualizadas'])if(!text.includes(phrase))throw Error(`${label}: Dashboard missing ${phrase}`);
  const restrictedLabels=await frame.locator('.v168-kpi-section.restricted .v168-kpi span').allTextContents();if(restrictedLabels.indexOf('Total em previdências')<restrictedLabels.indexOf('Novartis'))throw Error(`${label}: pension total was not moved after its components`);
  const route=name=>viewport.width<=520?frame.locator(`#dx1MobileNav [data-mobile-route="${name}"]`):frame.locator(`.nav [data-v="${name}"]`);
  await route('Despesas').click();await frame.waitForFunction(()=>window.__LTS_V168_STATE?.expense?.data?.management_groups);text=semantic(await frame.locator('.v168-expenses').innerText());for(const phrase of ['maiores grupos gerenciais','financiamentos auditados','consignado · coopharma','itens de o parque/cipó 396'])if(!text.includes(phrase))throw Error(`${label}: Expenses missing ${phrase}`);await frame.locator('.v168-tabs [data-v168-exp-tab="categories"]').click();if(await frame.locator('.v170-management-card').count()!==1)throw Error(`${label}: management-group card missing`);
  await route('Patrimônio').click();await frame.waitForFunction(()=>window.__LTS_V168_STATE?.wealth?.data?.morgan_statement);text=semantic(await frame.locator('.v168-wealth').innerText());for(const phrase of ['ativos já adquiridos','vestings ainda condicionais','saldo atual separado de parcelas futuras'])if(!text.includes(phrase))throw Error(`${label}: Wealth guide missing ${phrase}`);await frame.locator('[data-v168-wealth-tab="rsu"]').click();await frame.locator('#v170AllAwardApply').waitFor({state:'visible'});text=semantic(await frame.locator('.v168-wealth').innerText());for(const phrase of ['total bruto do extrato',semantic(brl(1745784.67)),'total considerado após reserva',semantic(brl(1569619.51)),'disponível agora',semantic(brl(15913.44)),'aplicar a todos os vestings','cotação individual'])if(!text.includes(phrase))throw Error(`${label}: Morgan panel missing ${phrase}`);
  if(label==='desktop'){await frame.locator('#v170AllAwardPrice').fill('20');await frame.locator('#v170AllAwardFx').fill('5.5');await frame.locator('#v170AllAwardApply').click();await frame.waitForFunction(()=>window.__LTS_V170_STATE?.globalAward?.saving===false&&window.__LTS_V170_STATE?.globalAward?.message);if(!awardMutations.some(x=>x.p_unit_price_usd===20&&x.p_fx_rate===5.5))throw Error('desktop: global award mutation was not sent');await page.screenshot({path:'v170-desktop-morgan.png',fullPage:true})}
  await route('Fluxo Diário').click();await frame.waitForFunction(()=>V==='Fluxo Diário'&&!FLOWLOADING&&FLOWTO==='2031-12-31'&&FLOWQ?.current_future?.days?.length);if(!flowCalls.some(x=>x.p_from==='2030-06-10'&&x.p_to==='2031-12-31'))throw Error(`${label}: default Flow range did not reach next year end`);text=semantic(await frame.locator('.wrap').innerText());if(!text.includes('base zero em 09/10/2013'))throw Error(`${label}: Flow missing historical-balance basis`);const flowHead=semantic(await frame.locator('.fx87-cons.fx87-head').textContent());for(const phrase of ['morgan disponível','saldo c/ morgan'])if(!flowHead.includes(phrase))throw Error(`${label}: Flow header missing ${phrase}`);const hist=frame.locator('#fv-2030-06-14,#d-2030-06-14').first();await hist.waitFor({state:'visible'});const histCells=await hist.locator(':scope > .fx87-cell').allTextContents();if([histCells[1],histCells[4]].some(value=>String(value).includes('—')))throw Error(`${label}: historical opening/closing balance is blank: ${JSON.stringify(histCells)}`);
  const transferDay=frame.locator('#d-2030-06-13');await transferDay.waitFor({state:'visible'});const transferCells=(await transferDay.locator(':scope > .fx87-cell').allTextContents()).map(semantic);for(const value of [brl(500),brl(300),brl(800)].map(semantic))if(!transferCells.includes(value))throw Error(`${label}: tracked-bank transfer arithmetic missing ${value}: ${JSON.stringify(transferCells)}`);if(!semantic(await transferDay.innerText()).includes('mov. interna líquida'))throw Error(`${label}: internal-net disclosure missing`);await transferDay.locator('.exp').click();await frame.waitForFunction(()=>[...document.querySelectorAll('.fx89-detail-row')].some(row=>/mov\. interna/i.test(row.textContent||'')&&/não é receita nem despesa/i.test(row.textContent||'')));
  const dims=await frame.locator('html').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));if(dims.scroll>dims.client+3)throw Error(`${label}: horizontal overflow ${JSON.stringify(dims)}`);if(errors.length)throw Error(`${label}: page errors ${JSON.stringify(errors)}`);const relevant=consoleErrors.filter(x=>!x.includes('favicon.ico'));if(relevant.length)throw Error(`${label}: console errors ${JSON.stringify(relevant)}`);if(label==='mobile')await page.screenshot({path:'v170-mobile-final.png',fullPage:true});await context.close();return{label,pass:true,viewport,flowCalls,awardMutations,requested:[...new Set(requested)]}
}

(async()=>{const browser=await chromium.launch({headless:true,...(process.env.LTS_CHROMIUM_EXECUTABLE?{executablePath:process.env.LTS_CHROMIUM_EXECUTABLE}:{})});try{const results=[await run(browser,{width:1440,height:1000},'desktop'),await run(browser,{width:390,height:844},'mobile')],output={pass:true,version:'v170-v169-review',data:'controlled-fixture-not-user-data-validation',results};fs.writeFileSync('v170-v169-review-result.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2))}catch(e){const output={pass:false,error:String(e.stack||e),data:'controlled-fixture-not-user-data-validation'};fs.writeFileSync('v170-v169-review-result.json',JSON.stringify(output,null,2));console.error(output.error);process.exitCode=1}finally{await browser.close()}})();
