const { chromium } = require('playwright');
const fs = require('fs');
const MARK='classification-save-refresh-self-heal-v1';
async function deepest(page){const chain=[];let f=page.mainFrame();for(let i=0;i<15;i++){chain.push(f.url());const kids=f.childFrames();if(!kids.length)break;f=kids[0]}return {f,chain}}
function item(key,label){return {description_key:key,merchant_name:label,example_description:label,card_name:'Visa Aeternum',due_date:'2026-09-25',occurrences:1,total_value:100,suggested_category:'Restaurantes',suggestion_confidence:.99,enrichment_confidence:.99,enrichment_evidence:'Evidência sintética para testar apenas o ciclo de UI.',merchant_identified:true,taxonomy_ambiguous:true,suggestion_safe:false}}
function data(withItem,key='lifecycle test',label='Lifecycle Test'){return {updates:{items:[],maintenance_checks:[],freshness:{position_as_of:'2026-09-02'}},semantic_review:{pending_groups:0,items:[]},card_classification_review:{pending_groups:withItem?1:0,pending_lines:withItem?1:0,pending_value:withItem?100:0,safe_suggestion_groups:0,category_options:['Restaurantes','Outros'],items:withItem?[item(key,label)]:[]},dashboard_cockpit:{version:'v148-smoke',as_of:'2026-09-02',status:'ok',liquidity:{through_d3:0,bank_cash:0,d0:0,d3_vested:0,fgts_d30:0},planning_audited:{},cards:{},work:{actionable_count:0,top_actions:[]},horizons:[],future_liquidity:[]},flow:{days:[],events:[]},card_history:{units:[]},card_operating:{},expenses:{},wealth:{},planning:{}}}
async function run(browser,viewport,label){const page=await browser.newPage({viewport});const errors=[];let f=null,chain=[],stage='open';page.on('pageerror',e=>errors.push(String(e?.stack||e)));try{await page.goto('http://127.0.0.1:8774/wip35-v148-candidate.html',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(5200);({f,chain}=await deepest(page));const expected=['wip35-v148-candidate.html','wip35-v147-candidate.html','wip35-v146-candidate.html','wip35-v142-candidate.html','wip35-v141-candidate.html','wip35-v140-candidate.html','wip35-v139-candidate.html','wip35-v138-candidate.html','wip35-v137-candidate.html','index.html'];const chainOk=expected.every((x,i)=>chain[i]?.includes(x));if(!chainOk)throw Error('chain mismatch '+JSON.stringify(chain));stage='install';await f.waitForFunction(m=>window.LTS_V148_CLASSIFICATION_LIFECYCLE===m&&window.__LTS_V148_SAVE_INSTALLED===m,MARK,{timeout:12000});
  await f.evaluate(d=>{
    sessionStorage.removeItem('lts_v148_classification_changes_v1');
    window.__LTS_V148_PENDING_VERIFICATION=null;
    window.__V148_MODE='success';
    window.__V148_CALLS={semantic:0,product:0};
    window.__V148_CLEAN=d.clean;
    window.S={...window.S,rpc:async(name,args)=>{
      if(name==='lts_browser_semantic_feedback_v1'){
        window.__V148_CALLS.semantic++;
        return {data:{ok:true},error:null};
      }
      if(name==='lts_browser_product_v1'){
        window.__V148_CALLS.product++;
        if(window.__V148_MODE==='fail-refresh')return {data:null,error:{message:'refresh synthetic failure'}};
        return {data:{mvp:window.__V148_CLEAN},error:null};
      }
      return {data:null,error:{message:'unexpected rpc '+name}};
    }};
    window.D=d.full;
    window.V='Atualizações';
    document.getElementById('nav')?.classList.remove('hidden');
    window.renderNav?.();
    window.render();
  }, {full:data(true),clean:data(false)});
  const row=f.locator('[data-v146-key="lifecycle test"]');stage='first-row';await row.waitFor({state:'visible',timeout:5000});stage='first-click';await row.locator('.cardclass-save').click();stage='first-confirmed';await f.waitForFunction(()=>window.__LTS_V148_CLASSIFICATION_STATE?.phase==='confirmed',undefined,{timeout:5000});stage='first-removed';await f.waitForFunction(()=>!document.querySelector('[data-v146-key="lifecycle test"]'),undefined,{timeout:5000});let first=await f.evaluate(()=>({state:window.__LTS_V148_CLASSIFICATION_STATE,calls:window.__V148_CALLS,banner:document.getElementById('v148WhatChanged')?.innerText||''}));if(first.calls.semantic!==1||first.calls.product!==1||!first.banner.includes('Lifecycle Test')||!first.banner.includes('1 → 0'))throw Error('success lifecycle mismatch '+JSON.stringify(first));
  await f.evaluate(d=>{window.__V148_MODE='fail-refresh';window.D=d;window.V='Atualizações';window.render()},data(true,'lifecycle retry','Lifecycle Retry'));
  const retryRow=f.locator('[data-v146-key="lifecycle retry"]');stage='retry-row';await retryRow.waitFor({state:'visible',timeout:5000});stage='retry-click';await retryRow.locator('.cardclass-save').click();stage='retry-pending';await f.waitForFunction(()=>window.__LTS_V148_CLASSIFICATION_STATE?.phase==='refresh_pending',undefined,{timeout:5000});let pending=await f.evaluate(()=>({state:window.__LTS_V148_CLASSIFICATION_STATE,calls:{...window.__V148_CALLS},banner:document.getElementById('v148WhatChanged')?.innerText||''}));if(pending.calls.semantic!==2||pending.calls.product!==2||!pending.banner.includes('Decisão salva')||!pending.banner.includes('Atualizar verificação'))throw Error('pending lifecycle mismatch '+JSON.stringify(pending));
  stage='manual-retry';await f.evaluate(()=>{window.__V148_MODE='success'});await f.locator('[data-v148-retry]').click();stage='retry-confirmed';await f.waitForFunction(()=>window.__LTS_V148_CLASSIFICATION_STATE?.phase==='confirmed'&&window.__LTS_V148_CLASSIFICATION_STATE?.key==='lifecycle retry',undefined,{timeout:5000});stage='retry-removed';await f.waitForFunction(()=>!document.querySelector('[data-v146-key="lifecycle retry"]'),undefined,{timeout:5000});const final=await f.evaluate(()=>({state:window.__LTS_V148_CLASSIFICATION_STATE,calls:window.__V148_CALLS,banner:document.getElementById('v148WhatChanged')?.innerText||'',status:window.__LTS_V148_CLASSIFICATION_STATUS}));if(final.calls.semantic!==2||final.calls.product!==3||!final.banner.includes('Lifecycle Retry')||final.status?.writer_repeated_on_refresh!==false||final.status?.permanent_polling!==false)throw Error('retry lifecycle mismatch '+JSON.stringify(final));if(errors.length)throw Error('browser errors '+JSON.stringify(errors));return {label,viewport,chain,chainOk,first,pending,final,errors,pass:true}}catch(e){let diagnostic={stage,label,viewport,chain,errors};if(f){try{diagnostic.runtime=await f.evaluate(()=>({state:window.__LTS_V148_CLASSIFICATION_STATE||null,calls:window.__V148_CALLS||null,pending:window.__LTS_V148_PENDING_VERIFICATION||null,installed:window.__LTS_V148_SAVE_INSTALLED||null,marker:window.LTS_V148_CLASSIFICATION_LIFECYCLE||null,view:String(window.V||''),rows:[...document.querySelectorAll('[data-v146-key]')].map(x=>x.getAttribute('data-v146-key')),banner:document.getElementById('v148WhatChanged')?.innerText||''}))}catch(snapshotError){diagnostic.snapshot_error=String(snapshotError?.stack||snapshotError)}}throw Error(String(e?.message||e)+'\nV148_DIAGNOSTIC='+JSON.stringify(diagnostic))}finally{await page.close()}}
(async()=>{const browser=await chromium.launch({headless:true});try{const desktop=await run(browser,{width:1440,height:900},'desktop');const mobile=await run(browser,{width:390,height:844},'mobile');const out={version:'v148-classification-lifecycle',marker:MARK,desktop,mobile,pass:true,importantLimit:'Synthetic browser lifecycle test. It mocks the existing RPC responses, verifies no duplicate writer call during refresh recovery, and is not authenticated E2E or a financial write.'};fs.writeFileSync('v148-classification-lifecycle-smoke-result.json',JSON.stringify(out,null,2));console.log('v148_classification_lifecycle_smoke=PASS')}finally{await browser.close()}})().catch(e=>{const out={version:'v148-classification-lifecycle',marker:MARK,pass:false,fatal:String(e?.stack||e)};try{fs.writeFileSync('v148-classification-lifecycle-smoke-result.json',JSON.stringify(out,null,2))}catch(_){}console.error(e);process.exit(1)});
