const { chromium } = require('playwright');
const fs = require('fs');
let currentStage='boot';
const write=o=>fs.writeFileSync('v151-dashboard-updates-smoke-result.json',JSON.stringify(o,null,2));
const stage=(label,msg)=>{currentStage=`${label}:${msg}`;console.log(`[v151-smoke] ${currentStage}`)};
const watchdog=setTimeout(()=>{const out={pass:false,watchdog:true,stage:currentStage,error:'v151 smoke exceeded 120s'};write(out);console.error(JSON.stringify(out));process.exit(124)},120000);
const has=(t,n)=>String(t||'').toLocaleLowerCase('pt-BR').includes(String(n||'').toLocaleLowerCase('pt-BR'));
async function deepest(page){let f=page.mainFrame(),chain=[];for(let i=0;i<18;i++){chain.push(f.url());const kids=f.childFrames();if(!kids.length)break;f=kids[0]}return {f,chain}}
async function deepestReady(page,label){for(let i=0;i<75;i++){const r=await deepest(page);try{if(await r.f.evaluate(()=>!!window.S&&typeof window.render==='function'&&typeof window.load==='function'))return r}catch(e){}await page.waitForTimeout(200)}throw Error(label+' app frame not ready')}
function data(){return {
  dashboard_cockpit:{version:'v151-smoke',as_of:'2026-09-03',liquidity:{through_d3:75133.58,bank_cash:19294.43,d0:42929.50,d3_vested:12909.65,fgts_d30:22432.31,accounts:[{institution:'Itaú',balance:15402.31},{institution:'Bradesco',balance:2931.96},{institution:'C6',balance:960.16}]},cards:{open_cycles_total:33328.63,closed_or_due_total:960.16,next_due:{due_date:'2026-09-08',amount:960.16,card_name:'C6 Carbon'}},work:{actionable_count:20,classification_groups:3,top_actions:[{title:'Revisar documento pendente',description:'Documento aguardando revisão'}]},planning_audited:{management_point_date:'2027-01-08',fgts_request_by:'2026-12-09',worst_before_brl:-25782.39,worst_after_brl:11262.25,covers_horizon:true,fgts_future_accrual_estimated:false},horizons:[{id:'30d',date:'2026-10-03',current_liquidity_balance:33219.79},{id:'90d',date:'2026-12-02',current_liquidity_balance:18560.47},{id:'year_end',date:'2026-12-31',current_liquidity_balance:4200.11}],wealth:{assets_central:5462642.63,known_debt_total:1890398.31,net_worth_central:3572244.32},expenses:{current_month:{spend:68000},previous_month:{spend:62000}}},
  wealth_executive:{summary:{assets_central:5462642.63,known_debt_total:1890398.31,net_worth_central:3572244.32},assets:{cipo_396:{market_central:5200000},volvo_xc40:{market_central:170000}}},
  updates:{items:[],maintenance_checks:[],freshness:{position_as_of:'2026-09-03'}},semantic_review:{pending_groups:0,items:[]},
  card_classification_review:{pending_groups:3,pending_lines:3,pending_value:1610.41,category_options:['Restaurantes','Moradia','Saúde'],items:[{description_key:'lavandex lavanderia lt',example_description:'LAVANDEX LAVANDERIA LT',total_value:380,merchant_name:'Lavandex Lavanderia LTDA',merchant_identified:true,enrichment_status:'identified_needs_taxonomy',enrichment_evidence:'CNAE Lavanderias',suggested_category:null},{description_key:'dufry lojas francas',example_description:'DUFRY LOJAS FRANCAS',total_value:297.64,merchant_name:'Dufry Lojas Francas',merchant_identified:true,enrichment_status:'identified_needs_context',enrichment_evidence:'loja franca duty free',suggested_category:null},{description_key:'sal gastronomia',example_description:'SAL GASTRONOMIA',total_value:933.38,merchant_name:'Sal Gastronomia',merchant_identified:true,enrichment_status:'taxonomy_review',enrichment_evidence:'restaurante',suggested_category:'Restaurantes',suggestion_confidence:.99}]},
  card_operating:{as_of:'2026-09-03',open_cycles_total:33328.63,open_cycles:[{card_name:'C6 Carbon',reference_month:'2026-09',due_date:'2026-09-08',amount:960.16,detail_preview_count:2}],next_due:{due_date:'2026-09-08',amount:960.16,card_name:'C6 Carbon'},contracted_installment_floor_total:2886.43,contracted_installment_floor_last_month:'2026-10',classification_review:{pending_lines:3,pending_groups:3,pending_value:1610.41}},
  card_history:{monthly:[{month:'2026-08',total:22000},{month:'2026-09',total:33328.63}],units:[]},flow:{days:[],events:[]},duplicate_quality_gate:{},expenses:{},wealth:{},planning:{}}
}
function matrix(){return {version:'expense-context-nature-matrix-v1',summary:{rows:629,total:722126.87,unassigned_rows:483,unassigned_total:360902.80},contexts:[{name:'Casa',rows:39,total:201241.45,categories:[{category:'Moradia',rows:8,total:29719.87}]},{name:'Benjamin',rows:65,total:64496.10,categories:[{category:'Educação',rows:18,total:45934.53}]}],categories:[{name:'Moradia',rows:8,total:29719.87,contexts:[{context:'Casa',rows:8,total:29719.87}]},{name:'Educação',rows:18,total:45934.53,contexts:[{context:'Benjamin',rows:18,total:45934.53}]}],unassigned_states:[{state:'documentary_detail_not_recovered',rows:16,total:186252.10},{state:'detail_available_system_review',rows:412,total:165493.93},{state:'classification_and_context_pending',rows:55,total:9156.77}],unassigned_categories:[]}}
function tx(){return [{date:'2028-04-12',description:'MASTERCARD FUTURO',account:'Itaú',direction:'saida',amount:1200,category:'Cartão',counterparty:'Mastercard',center_cost:'Lucas',source:'commitments',source_ref:'mc-future'},{date:'2013-11-01',description:'MASTERCARD HISTÓRICO',account:'Itaú',direction:'saida',amount:500,category:'Cartão',counterparty:'Mastercard',center_cost:'Lucas',source:'ledger',source_ref:'mc-2013'}]}
function planning(){return {summary:{first_management_point_date:'2027-01-08'},management_episodes:[{start_date:'2027-01-12',end_date:'2027-01-18',worst_balance:-25782.39}]}}
function wealth(){return {wealth:{as_of:'2026-09-03',summary:{net_worth_central:3572244.32,net_worth_low:3400000,net_worth_high:3700000,assets_central:5462642.63,known_debt_total:1890398.31,liquidity_through_d3:75133.58,restricted_contingency:22432.31,future_awards_excluded:100000},liquidity:{d3:32772.3},assets:{cipo_396:{market_central:5200000,documentary_debt:1800000,equity_central:3400000,historical_purchase_plus_reform:1000000,contract_final_due:'2029-12-01',loaded_exact_schedule_through:'2027-01-01'},volvo_xc40:{market_central:170000,documented_financed_balance:90000}},scheduled_commitments_not_counted_as_current_debt:[]},rsu:{vested_positions:[{units:459.483,value_brl:32772.3}],future_schedule:[],future_schedule_count:0},volvo_financing:{installment_amount:2886.43,next_due:'2026-09-08',total_installments:60,remaining_installments:60,future_schedule_total:173185.8},documentary_commitments:{items:[{commitment_id:'cipo_396',schedule_loaded:{next_amount:10000,next_date:'2026-09-10'}}]},cipo:{components:[]}}}
async function view(f,v){await f.evaluate(x=>{window.V=x;window.renderNav?.();window.render();window.__LTS_V150_AFTER_RENDER?.();window.__LTS_V151_AFTER_RENDER?.();window.__LTS_V151_LEDGER_SEARCH_AFTER_RENDER?.();window.__LTS_V151_WRAPPER_REPAINT?.()},v)}
async function run(browser,viewport,label){
  stage(label,'open');const page=await browser.newPage({viewport}),errors=[];page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.goto('http://127.0.0.1:8777/wip35-v151-candidate.html',{waitUntil:'domcontentloaded',timeout:25000});
  const {f,chain}=await deepestReady(page,label);stage(label,'frame-ready');if(!chain[0].includes('wip35-v151-candidate.html')||!chain.some(x=>x.includes('wip35-v150-candidate.html')))throw Error(label+' invalid frame chain');
  const D=data(),M=matrix(),T=tx(),P=planning(),W=wealth();
  await f.evaluate(async({D,M,T,P,W})=>{
    window.__V151_RPC_CALLS=[];
    const originalGetSession=window.S.auth?.getSession;
    if(window.S.auth)window.S.auth.getSession=async()=>({data:{session:{access_token:'v151-smoke'}},error:null});
    window.S.rpc=async(name,args)=>{window.__V151_RPC_CALLS.push({name,args});if(name==='lts_browser_product_v1')return {data:{mvp:D},error:null};if(name==='lts_browser_expense_context_nature_v1')return {data:M,error:null};if(name==='lts_browser_expense_drilldown_v1')return {data:{rows:[{date:'2026-09-02',description:'ALUGUEL TESTE',display_name:'Moradia · aluguel',center:'Casa',counterparty:'Imobiliária',amount:3500}]},error:null};if(name==='lts_browser_transactions_v1'){const rows=String(args?.p_query||'').toLowerCase().includes('mastercard')?T:[];return {data:{ok:true,total:rows.length,limit:args?.p_limit||200,offset:args?.p_offset||0,rows},error:null}};if(name==='lts_browser_planning_bridge_executive_v1')return {data:P,error:null};if(name==='lts_browser_wealth_detail_v1')return {data:W,error:null};if(name==='lts_browser_flow_v4')return {data:{ok:true,flow:{historical:{events:[]},current_future:{events:[]}}},error:null};return {data:{ok:true},error:null}};
    if(typeof window.load!=='function')throw Error('lexical product load unavailable');
    await window.load();
    await new Promise(r=>setTimeout(r,60));
    window.__V151_BOOT_RPC_CALLS=(window.__V151_RPC_CALLS||[]).slice();
    window.__V151_RPC_CALLS=[];
    window.__V151_ORIGINAL_GET_SESSION=originalGetSession||null;
  }, {D,M,T,P,W});
  stage(label,'product-loaded');
  await f.waitForFunction(()=>window.LTS_V151_COCKPIT==='dashboard-updates-cockpit-v1'&&window.LTS_V151_LEDGER_SEARCH==='ledger-search-export-v1'&&window.LTS_V151_REFERENCE_FIDELITY==='reference-fidelity-v1',null,{timeout:15000});stage(label,'layers-ready');
  await f.evaluate(D=>{window.D=D;window.__V150_EXP=null;window.dashboard=window.__LTS_V151_DASHBOARD_FN;window.__v143Dashboard=window.__LTS_V151_DASHBOARD_FN;window.render()},D);await view(f,'Dashboard');
  await f.waitForFunction(()=>window.__LTS_V151_REFERENCE_STATUS?.first_negative_date==='2027-01-12'&&document.getElementById('v151ExpenseLens'),null,{timeout:10000});stage(label,'dashboard-ready');
  let text=await f.locator('body').innerText();for(const needle of ['Sua vida financeira, em uma tela.','Disponível D+3','22.432,31','Primeiro saldo negativo','12/01/2027','sem estimar aportes futuros','Abra o número até os lançamentos','Moradia'])if(!has(text,needle))throw Error(label+' dashboard missing '+needle);
  if(has(text,'32.309,05')||has(text,'11.262,25')||has(text,'Pior após cobertura'))throw Error(label+' stale FGTS projection visible');
  await f.locator('[data-v151-exp-cat]').first().click();await f.waitForSelector('#v151ExpenseDrill',{timeout:5000});text=await f.locator('#v151ExpenseDrill').innerText();if(!has(text,'ALUGUEL TESTE')&&!has(text,'Moradia · aluguel'))throw Error(label+' dashboard drilldown did not reach transactions');stage(label,'dashboard-drilldown-pass');
  if(label==='mobile'){const ow=await f.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));if(ow.sw>ow.cw+12)throw Error('mobile dashboard horizontal overflow '+JSON.stringify(ow))}
  await view(f,'Atualizações');await f.waitForSelector('#v151LedgerSearch',{timeout:8000});await f.waitForSelector('#v151UpdateSummary',{timeout:8000});const input=f.locator('#v151LedgerTerm');await input.fill('Mastercard');await f.waitForFunction(()=>window.__LTS_V151_LEDGER_SEARCH_STATUS?.pass===true&&window.__LTS_V151_LEDGER_SEARCH_STATUS?.query==='Mastercard',null,{timeout:7000});text=await f.locator('#v151LedgerSearch').innerText();for(const needle of ['2 lançamento','MASTERCARD FUTURO','MASTERCARD HISTÓRICO','Exportar para Excel'])if(!has(text,needle))throw Error(label+' ledger missing '+needle);stage(label,'ledger-pass');
  await view(f,'Despesas');await f.waitForSelector('#v151ExpenseState',{timeout:8000});text=await f.locator('body').innerText();for(const needle of ['Histórico sem detalhe recuperado','LTS ainda investigando','Realmente para classificar/contextualizar'])if(!has(text,needle))throw Error(label+' expenses missing '+needle);stage(label,'expenses-pass');
  await view(f,'Cartões');await page.waitForTimeout(250);text=await f.locator('body').innerText();if(!has(text,'Cartões')||(!has(text,'faturas abertas')&&!has(text,'cartão × mês')))throw Error(label+' cards cockpit missing');stage(label,'cards-pass');
  await view(f,'Patrimônio');await f.waitForFunction(()=>document.body.innerText.toLowerCase().includes('patrimônio'),null,{timeout:6000});text=await f.locator('body').innerText();if(!has(text,'Patrimônio')||(!has(text,'RSU')&&!has(text,'CIPÓ 396')))throw Error(label+' wealth cockpit missing');stage(label,'wealth-pass');
  const state=await f.evaluate(()=>({v151:window.__LTS_V151_STATUS,ref:window.__LTS_V151_REFERENCE_STATUS,calls:window.__V151_RPC_CALLS||[],bootCalls:window.__V151_BOOT_RPC_CALLS||[],observer:!!window.__LTS_V151_DECORATION_OBSERVER}));if(state.v151?.financial_writer_changed!==false||state.v151?.classification_inference!==false||state.ref?.financial_writer_changed!==false||state.ref?.permanent_polling!==false||state.observer)throw Error('guardrails '+JSON.stringify(state));const forbidden=state.calls.map(x=>x.name).filter(x=>/apply|approve|write|feedback/i.test(x));if(forbidden.length)throw Error('writer RPC '+forbidden.join(','));if(state.calls.some(x=>x.name==='lts_browser_flow_v4'))throw Error('legacy broad flow called during v151 interactions');if(!state.bootCalls.some(x=>x.name==='lts_browser_product_v1'))throw Error('product bootstrap did not use mocked product RPC');if(errors.length)throw Error('browser errors '+JSON.stringify(errors));
  await page.close();stage(label,'complete');return {label,viewport,pass:true,first_negative:'2027-01-12',dashboard_drilldown:true,ledger:true,cards:true,wealth:true,rpc:state.calls.map(x=>x.name),bootstrapRpc:state.bootCalls.map(x=>x.name)}
}
(async()=>{const browser=await chromium.launch({headless:true});try{const results=[];for(const cfg of [[{width:1440,height:900},'desktop'],[{width:390,height:844},'mobile']])results.push(await run(browser,cfg[0],cfg[1]));const out={pass:true,version:'v151-reference-fidelity-ledger-search',results};write(out);console.log(JSON.stringify(out,null,2))}catch(e){const out={pass:false,stage:currentStage,error:String(e?.stack||e)};write(out);console.error(out.error);process.exitCode=1}finally{clearTimeout(watchdog);await browser.close()}})();