'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root='releases/'+(process.env.LTS_RELEASE||'v229');
const money=x=>x==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(x);
const num=x=>x==null?null:Number(x);
const expenseSource=fs.readFileSync(root+'/lts-v183-v168-feedback-safe.js','utf8');
const start=expenseSource.indexOf('    function expenseOverviewV168'),end=expenseSource.indexOf('\n',start);
const scope=vm.createContext({st:{expense:{key:'ytd'}},expenseRange:()=>({from:'2026-01-01',to:'2026-09-28'}),arr:x=>Array.isArray(x)?x:[],num,esc:x=>String(x??''),date:x=>x,money,pct:x=>x+'%',month:x=>x,kpi:()=>'',expenseTimeline:()=>({unit:'mensal',title:'Despesas',rows:[]}),expenseBarChart:()=>'',rankRows:()=>''});
vm.runInContext(expenseSource.slice(start,end)+';this.overview=expenseOverviewV168',scope);
const report={period:{label:'Ano 2026'},summary:{selected_total:75,last_12m:12345.67},comparison:{previous_total:100,variation_pct:-25,partial:true},monthly_detail:[{month:'2026-09-01',total:75}]};
let html=scope.overview(report);assert(html.includes('Ano 2026'));assert(html.includes('-25%'));assert(html.includes(money(12345.67)));assert(html.includes('até o mesmo dia'));assert(!html.includes('undefined'));
html=scope.overview({summary:{},comparison:{},monthly_detail:[]});assert(html.includes('Sem base comparável'));assert(html.includes('Sem base disponível'));assert(html.includes('2026-01-01 → 2026-09-28'));assert(!html.includes('undefined'));
const source=fs.readFileSync(root+'/lts-v179-cash-recovery.js','utf8'),a=source.indexOf('  function decorateFlow(){'),b=source.indexOf('  function cleanTechnical(){',a);
const positions=[['2026-11-05',1100],['2026-11-06',1100],['2026-11-07',1100],['2026-11-08',1600],['2026-11-09',1600],['2026-11-10',2300],['2026-11-11',2300]];
const rows=positions.map(([date,rsu])=>({id:'d-'+date,children:Array.from({length:11},(_,i)=>({textContent:i===7?money(rsu):i===8?money(rsu-1000):i===10?money(rsu+4000):'',classList:{remove(){},toggle(){}}}))}));
const s=vm.createContext({V:'Fluxo Diário',document:{querySelectorAll:q=>q.includes('fx87-row')?rows:[]},state:{awards:{status:'ready',data:{as_of:'2026-09-20',brokerage_available:1100,events:[{regular_rsu:true,vesting_date:'2026-11-05',available_date:'2026-11-08',value:500},{regular_rsu:true,vesting_date:'2026-11-07',available_date:'2026-11-10',value:700}]}}},mergedFlowDays:()=>positions.map(([date,value])=>({date,fix86_columns:{rsus_vested:value}})),finite:num,arr:x=>x||[],total:xs=>xs.reduce((n,x)=>n+x,0),money,EXP:new Set()});
vm.runInContext(source.slice(a,b)+';decorateFlow()',s);
rows.forEach((row,i)=>{const rsu=positions[i][1];assert.equal(row.children[7].textContent,money(rsu),'availability date controls the displayed RSU');assert.equal(row.children[8].textContent,money(rsu-1000),'the same position is used by the following total');assert.equal(row.children[10].textContent,money(rsu+4000));});
const out={pass:true,vesting_and_following_days:positions.length,availability_preserved:true,expense_period_label:true,comparison_missing_is_not_zero:true,last_12_months:true};
fs.mkdirSync('qa',{recursive:true});fs.writeFileSync('qa/v229-reliability-result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));
