-- Optional bounded exact-text transport. READ ONLY, at most six closed runs.
-- Bind owner_id, project_ref and six run UUID parameters from the inventory.
-- Repeated placeholders can represent a smaller batch (IN has set semantics).
-- DISTINCT uses the COMPLETE scoped JSONB array of eight exact text values,
-- NOT raw hashes. Actions/run/timestamps remain per-observation references.
-- SQL independently hashes all twelve ordered source text fields for each run.
-- expand-transport must validate hashes, counts and exact inventory metadata;
-- it creates retained export-v2 sources, and never overwrites prior exports.
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY; SET LOCAL statement_timeout='20000'; SET LOCAL work_mem='32MB'; SET LOCAL timezone='UTC'; SET LOCAL max_parallel_workers_per_gather=0;
WITH data AS MATERIALIZED(
 SELECT o.id::text id,o.user_id::text user_id,o.connection_id::text connection_id,o.sync_run_id::text sync_run_id,o.resource_type,o.provider_record_id,o.raw_hash,o.raw_payload::text raw_payload,o.normalized_payload::text normalized_payload,o.reconciliation::text reconciliation,o.ingest_action,o.observed_at::text observed_at
 FROM public.lts_open_finance_observation o WHERE o.sync_run_id IN (:'run_id_1'::uuid, :'run_id_2'::uuid, :'run_id_3'::uuid, :'run_id_4'::uuid, :'run_id_5'::uuid, :'run_id_6'::uuid) AND o.user_id=:'owner_id'
),content AS MATERIALIZED(SELECT DISTINCT jsonb_build_array(d.user_id,d.connection_id,d.resource_type,d.provider_record_id,d.raw_hash,d.raw_payload,d.normalized_payload,d.reconciliation) value FROM data d),versions AS MATERIALIZED(SELECT (row_number() OVER(ORDER BY value)-1) slot,value FROM content)
SELECT jsonb_build_object('format','lts-observation-transport-v248','owner_id',:'owner_id','source_project',:'project_ref','exported_at',now()::text,'versions',coalesce((SELECT jsonb_agg(value ORDER BY slot) FROM versions),'[]'::jsonb),'runs',(SELECT jsonb_agg(jsonb_build_object('run_metadata',to_jsonb(r)::text,'row_count',(SELECT count(*) FROM data d WHERE d.sync_run_id=r.id::text),'source_vectors_sha256',(SELECT encode(pg_catalog.sha256(convert_to(coalesce(string_agg(array_to_json(ARRAY[d.id,d.user_id,d.connection_id,d.sync_run_id,d.resource_type,d.provider_record_id,d.raw_hash,d.raw_payload,d.normalized_payload,d.reconciliation,d.ingest_action,d.observed_at])::text,E'\n' ORDER BY d.id),''),'UTF8')),'hex') FROM data d WHERE d.sync_run_id=r.id::text),'references',coalesce((SELECT jsonb_agg(jsonb_build_array(d.id,d.sync_run_id,d.ingest_action,d.observed_at,v.slot) ORDER BY d.id) FROM data d JOIN versions v ON v.value=jsonb_build_array(d.user_id,d.connection_id,d.resource_type,d.provider_record_id,d.raw_hash,d.raw_payload,d.normalized_payload,d.reconciliation) WHERE d.sync_run_id=r.id::text),'[]'::jsonb)) ORDER BY r.id) FROM public.lts_open_finance_sync_run r WHERE r.user_id=:'owner_id' AND r.id IN(:'run_id_1'::uuid, :'run_id_2'::uuid, :'run_id_3'::uuid, :'run_id_4'::uuid, :'run_id_5'::uuid, :'run_id_6'::uuid))) AS transport; ROLLBACK;
