import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { unzipSync, strFromU8 } from 'npm:fflate@0.8.2';

type Preview={detected_format:string;detected_schema:string|null;row_count:number|null;column_names:string[];sample:unknown;date_min:string|null;date_max:string|null;status:'inspected'|'ready_for_parser'|'needs_specialized_parser'|'review_required'|'failed';warnings:string[];error_message?:string|null};
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}});

function splitCsvLine(line:string,delimiter:string){const out:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++}else quote=!quote}else if(c===delimiter&&!quote){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim().length);if(!lines.length)return{headers:[],rows:[] as Record<string,string>[],delimiter:',',totalLines:0};const delimiter=[',',';','\t'].map(d=>({d,n:splitCsvLine(lines[0],d).length})).sort((a,b)=>b.n-a.n)[0].d;const headers=splitCsvLine(lines[0],delimiter).map((h,i)=>h||`column_${i+1}`).slice(0,80),rows:Record<string,string>[]=[];for(const line of lines.slice(1,50001)){const vals=splitCsvLine(line,delimiter),obj:Record<string,string>={};headers.forEach((h,i)=>obj[h]=vals[i]??'');rows.push(obj)}return{headers,rows,delimiter,totalLines:Math.max(lines.length-1,0)}}
function safeDate(v:unknown):string|null{if(typeof v!=='string')return null;const s=v.trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const br=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(br){const dd=Number(br[1]),mm=Number(br[2]);if(dd>=1&&dd<=31&&mm>=1&&mm<=12)return`${br[3]}-${br[2]}-${br[1]}`}return null}
function dateRange(rows:Record<string,unknown>[],headers:string[]){const h=headers.find(x=>/^(date|data|day|dia|entry date|food date)$/i.test(x.trim()))||headers.find(x=>/date|data/i.test(x));if(!h)return{date_min:null,date_max:null};const dates=rows.map(r=>safeDate(r[h])).filter((x):x is string=>!!x).sort();return{date_min:dates[0]||null,date_max:dates.at(-1)||null}}
function detectSchema(sourceType:string,format:string,headers:string[],sample:unknown):string|null{const h=headers.map(x=>x.toLowerCase());if(sourceType==='myfitnesspal'&&format==='csv'){if(h.some(x=>x.includes('calorie'))&&h.some(x=>x.includes('date')))return'myfitnesspal_nutrition_candidate';if(h.some(x=>x.includes('meal'))||h.some(x=>x.includes('food')))return'myfitnesspal_food_candidate';return'myfitnesspal_csv_unknown'}if(sourceType==='apple_health'&&format==='xml')return'apple_health_export_candidate';if(sourceType==='polar'&&(format==='csv'||format==='json'))return'polar_export_candidate';if(sourceType==='lab')return format==='pdf'||format==='image'?'lab_document':'lab_structured_candidate';if(sourceType==='body_composition')return'body_composition_candidate';if(sourceType==='training')return'training_candidate';if(sample&&format==='json')return`${sourceType||'generic'}_json_candidate`;return null}
const norm=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const header=(headers:string[],patterns:RegExp[])=>headers.find(h=>patterns.some(p=>p.test(norm(h))))||null;
function num(v:unknown):number|null{if(v==null)return null;let s=String(v).trim().replace(/[^0-9,.-]/g,'');if(!s)return null;if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,'');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}
function xmlAttrs(tag:string){const out:Record<string,string>={};for(const m of tag.matchAll(/([A-Za-z0-9_:-]+)="([^"]*)"/g))out[m[1]]=m[2];return out}
function appleEpoch(s:string|undefined):number|null{if(!s)return null;const m=s.match(/^(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2}) ([+-]\d{2})(\d{2})$/);const iso=m?`${m[1]}T${m[2]}${m[3]}:${m[4]}`:s.replace(' ','T');const t=Date.parse(iso);return Number.isFinite(t)?t:null}

async function importMfp(sb:any,userId:string,upload:any,headers:string[],rows:Record<string,string>[]){
 const dateH=header(headers,[/^date$/,/^data$/,/^food date$/,/^entry date$/]),calH=header(headers,[/^calories?$/,/^calories kcal$/,/^energy kcal$/,/^kcal$/]),proteinH=header(headers,[/^protein$/,/^protein g$/,/^proteina$/,/^proteina g$/]),carbsH=header(headers,[/^carbohydrates?$/,/^carbs?$/,/^carbohydrates g$/,/^carbs g$/,/^carboidratos?$/]),fatH=header(headers,[/^fat$/,/^fat g$/,/^gordura$/,/^gorduras$/]),fiberH=header(headers,[/^fiber$/,/^fiber g$/,/^fibra$/,/^fibras$/]);
 if(!dateH||!calH||(!proteinH&&!carbsH&&!fatH))return{imported:0,reason:'required_columns_not_recognized',mapping:{dateH,calH,proteinH,carbsH,fatH,fiberH}};
 const by=new Map<string,{cal:number,protein:number|null,carbs:number|null,fat:number|null,fiber:number|null,rows:number}>();let rejectedDates=0;
 for(const r of rows){const d=safeDate(r[dateH]);if(!d){rejectedDates++;continue}const c=num(r[calH]);if(c==null)continue;const cur=by.get(d)||{cal:0,protein:proteinH?0:null,carbs:carbsH?0:null,fat:fatH?0:null,fiber:fiberH?0:null,rows:0};cur.cal+=c;if(proteinH){const x=num(r[proteinH]);if(x!=null)cur.protein=(cur.protein||0)+x}if(carbsH){const x=num(r[carbsH]);if(x!=null)cur.carbs=(cur.carbs||0)+x}if(fatH){const x=num(r[fatH]);if(x!=null)cur.fat=(cur.fat||0)+x}if(fiberH){const x=num(r[fiberH]);if(x!=null)cur.fiber=(cur.fiber||0)+x}cur.rows++;by.set(d,cur)}
 if(!by.size)return{imported:0,reason:rejectedDates?'unrecognized_date_format':'no_valid_rows',mapping:{dateH,calH,proteinH,carbsH,fatH,fiberH}};
 const records=[...by.entries()].map(([d,x])=>({user_id:userId,source_record_id:`mfp:${d}`,nutrition_date:d,calories_kcal:x.cal,protein_g:x.protein,carbs_g:x.carbs,fat_g:x.fat,fiber_g:x.fiber,source:'MyFitnessPal export',source_file:upload.original_filename,confidence:'high',notes:'Valores agregados por data diretamente do arquivo importado; nenhum macro ausente foi estimado.',source_payload:{upload_id:upload.id,source_rows:x.rows,mapping:{date:dateH,calories:calH,protein:proteinH,carbs:carbsH,fat:fatH,fiber:fiberH}}}));
 const{error}=await sb.from('health_daily_nutrition').upsert(records,{onConflict:'user_id,source_record_id'});if(error)return{imported:0,reason:error.message,mapping:{dateH,calH,proteinH,carbsH,fatH,fiberH}};
 await sb.from('health_data_requests').update({status:'completed',completed_at:new Date().toISOString(),notes:`MyFitnessPal importado: ${records.length} dia(s) reconhecido(s) no arquivo mais recente. Dados ausentes não foram estimados.`}).eq('domain','nutrition');
 return{imported:records.length,reason:null,mapping:{dateH,calH,proteinH,carbsH,fatH,fiberH},rejectedDates};
}
async function inspectMfpCsv(sb:any,user:any,upload:any,text:string,pWarnings:string[]){const parsed=parseCsv(text),sample=parsed.rows.slice(0,5),range=dateRange(parsed.rows,parsed.headers),schema=detectSchema('myfitnesspal','csv',parsed.headers,sample);let p:Preview={detected_format:'csv',detected_schema:schema,row_count:parsed.totalLines,column_names:parsed.headers,sample,date_min:range.date_min,date_max:range.date_max,status:'ready_for_parser',warnings:pWarnings};let autoImport:any=null;if(parsed.headers.length<2){p.status='review_required';p.warnings.push('CSV com poucas colunas detectadas.')}if(schema==='myfitnesspal_nutrition_candidate'){autoImport=await importMfp(sb,user.id,upload,parsed.headers,parsed.rows);if(autoImport.imported>0)p.warnings.push(`${autoImport.imported} dia(s) nutricional(is) importado(s) automaticamente.`);else{p.status='review_required';p.warnings.push(`MyFitnessPal reconhecido, mas importação automática retida: ${autoImport.reason}.`)}}return{p,autoImport}}

async function importAppleHealth(sb:any,userId:string,upload:any,text:string){
 const metrics:any[]=[];let activityDays=0,sleepDays=0;let dateMin:string|null=null,dateMax:string|null=null;
 const activityTags=text.match(/<ActivitySummary\b[^>]*\/?\s*>/g)||[];
 for(const tag of activityTags){const a=xmlAttrs(tag),d=safeDate(a.dateComponents);if(!d)continue;const vals=[['active_energy_kcal',num(a.activeEnergyBurned),a.activeEnergyBurnedUnit||'kcal'],['exercise_minutes',num(a.appleExerciseTime),'min'],['stand_hours',num(a.appleStandHours),'h']] as const;let any=false;for(const [metric,value,unit] of vals){if(value==null)continue;any=true;metrics.push({user_id:userId,source_record_id:`apple_health:${metric}:${d}`,measured_at:`${d}T12:00:00Z`,metric_type:metric,value,unit,source:'Apple Health export',source_file:upload.original_filename,confidence:'high',notes:'Valor diário proveniente de ActivitySummary do export Apple Health.',source_payload:{upload_id:upload.id,method:'ActivitySummary'}})}if(any){activityDays++;dateMin=!dateMin||d<dateMin?d:dateMin;dateMax=!dateMax||d>dateMax?d:dateMax}}
 const sleepBy=new Map<string,{start:number;end:number}[]>();
 const recordTags=text.match(/<Record\b[^>]*>/g)||[];
 for(const tag of recordTags){if(!tag.includes('HKCategoryTypeIdentifierSleepAnalysis'))continue;const a=xmlAttrs(tag);if(!/SleepAnalysisAsleep/i.test(a.value||''))continue;const st=appleEpoch(a.startDate),en=appleEpoch(a.endDate),d=safeDate(a.endDate);if(st==null||en==null||en<=st||!d)continue;const arr=sleepBy.get(d)||[];arr.push({start:st,end:en});sleepBy.set(d,arr)}
 for(const [d,intervals] of sleepBy){intervals.sort((x,y)=>x.start-y.start);let total=0,cs=intervals[0].start,ce=intervals[0].end;for(const it of intervals.slice(1)){if(it.start<=ce){ce=Math.max(ce,it.end)}else{total+=ce-cs;cs=it.start;ce=it.end}}total+=ce-cs;const hours=total/3600000;if(hours<=0||hours>24)continue;metrics.push({user_id:userId,source_record_id:`apple_health:sleep_duration_h:${d}`,measured_at:`${d}T12:00:00Z`,metric_type:'sleep_duration_h',value:Math.round(hours*100)/100,unit:'h',source:'Apple Health export',source_file:upload.original_filename,confidence:'medium',notes:'Duração de sono calculada pela união de intervalos categorizados como asleep; intervalos sobrepostos não são somados duas vezes.',source_payload:{upload_id:upload.id,method:'sleep_interval_union',interval_count:intervals.length}});sleepDays++;dateMin=!dateMin||d<dateMin?d:dateMin;dateMax=!dateMax||d>dateMax?d:dateMax}
 if(metrics.length){const{error}=await sb.from('health_metrics').upsert(metrics,{onConflict:'user_id,source_record_id'});if(error)return{imported:0,activityDays:0,sleepDays:0,reason:error.message,dateMin,dateMax};const complete=activityDays>0&&sleepDays>0;await sb.from('health_data_requests').update({status:complete?'completed':'partial',completed_at:complete?new Date().toISOString():null,notes:`Apple Health importado: ${activityDays} dia(s) de ActivitySummary e ${sleepDays} dia(s) com sono reconhecido. Passos granulares foram preservados no arquivo, mas não somados automaticamente para evitar dupla contagem entre fontes/dispositivos.`}).eq('domain','activity_sleep')}
 return{imported:metrics.length,activityDays,sleepDays,reason:metrics.length?null:'no_supported_daily_metrics',dateMin,dateMax};
}

async function inspectAppleXml(sb:any,user:any,upload:any,text:string,warnings:string[]){const recordCount=(text.match(/<Record\b/g)||[]).length,activityCount=(text.match(/<ActivitySummary\b/g)||[]).length;const autoImport=await importAppleHealth(sb,user.id,upload,text);const p:Preview={detected_format:'xml',detected_schema:'apple_health_export_candidate',row_count:recordCount||activityCount||null,column_names:[],sample:{records:recordCount,activity_summaries:activityCount},date_min:autoImport.dateMin,date_max:autoImport.dateMax,status:autoImport.imported>0?'inspected':'review_required',warnings:[...warnings,`${recordCount} Record(s) e ${activityCount} ActivitySummary(s) detectados.`,autoImport.imported>0?`${autoImport.imported} métrica(s) diária(s) normalizada(s): atividade ${autoImport.activityDays} dia(s), sono ${autoImport.sleepDays} dia(s).`:'Nenhuma métrica diária suportada pôde ser normalizada automaticamente.','Passos granulares não são somados automaticamente nesta fase porque múltiplas fontes/dispositivos podem se sobrepor no export.']};return{p,autoImport}}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'missing_authorization'},401);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,sb=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});
 const{data:{user},error:userError}=await sb.auth.getUser();if(userError||!user)return json({error:'invalid_user'},401);
 let body:any={};try{body=await req.json()}catch{return json({error:'invalid_json'},400)}const uploadId=String(body.upload_id||'');if(!uploadId)return json({error:'upload_id_required'},400);
 const{data:upload,error:uploadError}=await sb.from('health_uploads').select('*').eq('id',uploadId).single();if(uploadError||!upload)return json({error:'upload_not_found'},404);if(upload.user_id!==user.id)return json({error:'forbidden'},403);
 const{data:file,error:downloadError}=await sb.storage.from('health-inbox').download(upload.storage_path);if(downloadError||!file)return json({error:'download_failed',detail:downloadError?.message||null},400);
 const mime=(upload.mime_type||file.type||'').toLowerCase(),name=(upload.original_filename||'').toLowerCase(),size=Number(upload.size_bytes||file.size||0);let p:Preview={detected_format:'binary',detected_schema:null,row_count:null,column_names:[],sample:null,date_min:null,date_max:null,status:'needs_specialized_parser',warnings:[]},autoImport:any=null;
 try{
  if(size>50*1024*1024)throw new Error('file_too_large');
  if(mime.includes('zip')||name.endsWith('.zip')){
   const bytes=new Uint8Array(await file.arrayBuffer()),archive=unzipSync(bytes),names=Object.keys(archive).filter(n=>!n.endsWith('/'));p={detected_format:'zip',detected_schema:`${upload.source_type||'generic'}_archive`,row_count:names.length,column_names:[],sample:{entries:names.slice(0,20)},date_min:null,date_max:null,status:'needs_specialized_parser',warnings:[`Arquivo compactado com ${names.length} item(ns).`]};
   if(upload.source_type==='myfitnesspal'){
    const nutritionName=names.find(n=>/nutrition/i.test(n)&&/\.csv$/i.test(n));if(nutritionName){const inspected=await inspectMfpCsv(sb,user,upload,strFromU8(archive[nutritionName]),[`CSV de nutrição encontrado dentro do ZIP: ${nutritionName}`]);p={...inspected.p,detected_format:'zip/csv',detected_schema:inspected.p.detected_schema?`zip:${inspected.p.detected_schema}`:'myfitnesspal_zip'};autoImport=inspected.autoImport}else{p.status='review_required';p.warnings.push('ZIP do MyFitnessPal identificado, mas nenhum CSV com “nutrition” no nome foi localizado.')}
   }else if(upload.source_type==='apple_health'){
    const xmlName=names.find(n=>/(^|\/)export\.xml$/i.test(n));if(xmlName){const inspected=await inspectAppleXml(sb,user,upload,strFromU8(archive[xmlName]),[`Apple Health export.xml localizado dentro do ZIP: ${xmlName}`]);p={...inspected.p,detected_format:'zip/xml'};autoImport=inspected.autoImport}else{p.status='review_required';p.warnings.push('ZIP Apple Health identificado, mas export.xml não foi localizado.')}
   }
  }else if(mime.includes('csv')||name.endsWith('.csv')){
   if(upload.source_type==='myfitnesspal'){const inspected=await inspectMfpCsv(sb,user,upload,await file.text(),size>8*1024*1024?['Preview limitado: arquivo de texto grande.']:[]);p=inspected.p;autoImport=inspected.autoImport}else{const parsed=parseCsv(await file.text()),sample=parsed.rows.slice(0,5),range=dateRange(parsed.rows,parsed.headers);p={detected_format:'csv',detected_schema:detectSchema(upload.source_type,'csv',parsed.headers,sample),row_count:parsed.totalLines,column_names:parsed.headers,sample,date_min:range.date_min,date_max:range.date_max,status:'ready_for_parser',warnings:[]}}
  }else if(mime.includes('json')||name.endsWith('.json')){
   const obj=JSON.parse(await file.text()),arr=Array.isArray(obj)?obj:(Array.isArray(obj?.data)?obj.data:null),first=arr?.[0]??obj,headers=first&&typeof first==='object'&&!Array.isArray(first)?Object.keys(first).slice(0,80):[],rows=(arr||[]).slice(0,20000).filter((x:any)=>x&&typeof x==='object'&&!Array.isArray(x)),range=dateRange(rows,headers);p={detected_format:'json',detected_schema:detectSchema(upload.source_type,'json',headers,first),row_count:arr?arr.length:1,column_names:headers,sample:arr?arr.slice(0,5):obj,date_min:range.date_min,date_max:range.date_max,status:'ready_for_parser',warnings:[]}
  }else if(mime.includes('xml')||name.endsWith('.xml')){
   if(upload.source_type==='apple_health'){const inspected=await inspectAppleXml(sb,user,upload,await file.text(),[]);p=inspected.p;autoImport=inspected.autoImport}else{const text=await file.text(),recordCount=(text.match(/<Record\b/g)||[]).length;p={detected_format:'xml',detected_schema:detectSchema(upload.source_type,'xml',[],null),row_count:recordCount||null,column_names:[],sample:null,date_min:null,date_max:null,status:'needs_specialized_parser',warnings:['Conteúdo XML identificado; valores individuais ainda não foram normalizados.']}}
  }else if(mime.includes('pdf')||name.endsWith('.pdf'))p={...p,detected_format:'pdf',detected_schema:detectSchema(upload.source_type,'pdf',[],null),warnings:['Documento preservado. Extração clínica requer parser específico e validação.']};
  else if(mime.startsWith('image/')||/\.(png|jpg|jpeg|heic)$/.test(name))p={...p,detected_format:'image',detected_schema:detectSchema(upload.source_type,'image',[],null),warnings:['Imagem preservada. Extração visual requer parser específico e validação.']};
 }catch(e){p.status='failed';p.error_message=e instanceof Error?e.message:String(e)}
 const payload={user_id:user.id,upload_id:upload.id,source_type:upload.source_type,parser_version:'inspect-v4',...p,updated_at:new Date().toISOString()};const{data:preview,error:previewError}=await sb.from('health_ingestion_previews').upsert(payload,{onConflict:'user_id,upload_id'}).select().single();if(previewError)return json({error:'preview_write_failed',detail:previewError.message},400);
 const uploadStatus=p.status==='failed'?'failed':autoImport?.imported>0?'processed':'inspected';await sb.from('health_uploads').update({status:uploadStatus,processed_at:new Date().toISOString()}).eq('id',upload.id);
 return json({ok:true,preview,auto_import:autoImport});
});