const healthConfig=window.LTS_HEALTH_CONFIG;
if(!healthConfig?.backend?.url||!healthConfig?.backend?.publishableKey)throw new Error('LTS Health backend configuration is missing.');
const SUPABASE_URL=healthConfig.backend.url;
const SUPABASE_KEY=healthConfig.backend.publishableKey;
const HEALTH_STORAGE_BUCKET=healthConfig.storageBucket||'health-inbox';
const HEALTH_INSPECT_FUNCTION=healthConfig.inspectFunction||'health-inspect-upload';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const q=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return'—';const s=String(v).slice(0,10),[y,m,d]=s.split('-');return y&&m&&d?`${d}/${m}/${y}`:s};
const fmtNum=(v,d=1)=>v==null||v===''?'—':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const daysAgo=v=>{if(!v)return null;const t=new Date(String(v).slice(0,10)+'T12:00:00').getTime();return Number.isFinite(t)?Math.floor((Date.now()-t)/86400000):null};
const empty=msg=>`<div class="empty">${esc(msg||'Nenhum registro disponível.')}</div>`;
const statusPill=s=>{const x=String(s||'').toLowerCase();return x==='completed'||x==='imported'||x==='validated'||x==='active'?'ok':x==='rejected'||x==='failed'||x==='quarantined'?'bad':'warn'};
let currentSession=null;
let state={};

function setView(session){currentSession=session;q('loginView').classList.toggle('hidden',!!session);q('app').classList.toggle('hidden',!session);if(session)loadAll()}
async function signIn(){q('loginMsg').textContent='Entrando…';const {error}=await sb.auth.signInWithPassword({email:q('email').value.trim(),password:q('password').value});q('loginMsg').textContent=error?error.message:''}
async function signOut(){await sb.auth.signOut()}
q('loginBtn').addEventListener('click',signIn);q('password').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});q('logoutBtn').addEventListener('click',signOut);

function activateTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));q(tab)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));
q('moreBtn')?.addEventListener('click',()=>activateTab('inbox'));

function safeName(name){return String(name||'arquivo').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
const sourceGuides={
 myfitnesspal:{title:'MyFitnessPal',what:'Envie CSV ou ZIP exportado. O parser agrega somente valores presentes no arquivo; macros ausentes não são estimados.',accept:['csv','zip','json']},
 lab:{title:'Exames históricos',what:'Envie PDF, imagem ou arquivo estruturado. O original fica preservado; biomarcadores só entram como estruturados com evidência suficiente.',accept:['pdf','jpg','jpeg','png','heic','csv','json']},
 apple_health:{title:'Apple Health',what:'Envie o ZIP de exportação ou export.xml. Atividade diária e sono suportado podem ser normalizados; passos sobrepostos entre dispositivos não são somados automaticamente.',accept:['zip','xml']},
 polar:{title:'Polar',what:'Envie CSV ou JSON exportado. Nesta fase o arquivo é inspecionado e preservado para parser especializado, sem completar métricas ausentes.',accept:['csv','json','zip']},
 body_composition:{title:'Bioimpedância',what:'Envie PDF, imagem, CSV ou JSON. O arquivo bruto permanece ligado à proveniência.',accept:['pdf','jpg','jpeg','png','heic','csv','json']},
 training:{title:'Treino',what:'Envie fonte estruturada ou documento bruto. Nenhuma carga ou repetição é convertida quando a unidade não está explícita.',accept:['csv','json','pdf','jpg','jpeg','png']},
 document:{title:'Outro documento',what:'O arquivo é preservado como evidência. Extração automática só ocorre quando houver parser validado para o formato.',accept:['pdf','jpg','jpeg','png','heic','csv','json','zip','xml']}
};
function ext(name){return String(name||'').toLowerCase().split('.').pop()||''}
function updateUploadGuide(){const g=sourceGuides[q('uploadType').value];q('uploadGuideTitle').textContent=g.title;q('uploadGuideText').textContent=g.what;q('uploadGuideFormats').textContent='Formatos esperados: '+g.accept.join(', ').toUpperCase()}
q('uploadType').addEventListener('change',updateUploadGuide);updateUploadGuide();

async function uploadFiles(){const files=[...(q('uploadFile').files||[])];if(!currentSession?.user||!files.length){setUploadMsg('Selecione pelo menos um arquivo.','bad');return}const guide=sourceGuides[q('uploadType').value];for(const file of files){if(file.size>50*1024*1024){setUploadMsg(`${file.name}: limite de 50 MB excedido.`,'bad');return}if(!guide.accept.includes(ext(file.name))){setUploadMsg(`${file.name}: formato não esperado para ${guide.title}.`,'bad');return}}
 q('uploadBtn').disabled=true;setUploadMsg('Enviando para armazenamento privado e inspecionando…','');let uploaded=0,inspected=0,imported=0,review=0;
 for(const file of files){const path=`${currentSession.user.id}/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${safeName(file.name)}`;const up=await sb.storage.from(HEALTH_STORAGE_BUCKET).upload(path,file,{upsert:false,contentType:file.type||undefined});if(up.error){setUploadMsg(`Falha em ${file.name}: ${up.error.message}`,'bad');continue}
  const meta=await sb.from('health_uploads').insert({user_id:currentSession.user.id,source_type:q('uploadType').value,original_filename:file.name,storage_path:path,mime_type:file.type||null,size_bytes:file.size,status:'uploaded',notes:'Recebido pelo Health Data Inbox v7'}).select().single();
  if(meta.error||!meta.data){await sb.storage.from(HEALTH_STORAGE_BUCKET).remove([path]);setUploadMsg(`Registro de ${file.name} falhou: ${meta.error?.message||'erro desconhecido'}`,'bad');continue}
  uploaded++;const inspect=await sb.functions.invoke(HEALTH_INSPECT_FUNCTION,{body:{upload_id:meta.data.id}});if(!inspect.error&&inspect.data?.ok){inspected++;if(inspect.data.upload_status==='imported')imported++;if(inspect.data.upload_status==='review_required')review++}else if(inspect.error){setUploadMsg(`${file.name} foi preservado, mas a inspeção falhou: ${inspect.error.message}`,'bad')}
 }
 q('uploadBtn').disabled=false;q('uploadFile').value='';if(uploaded)setUploadMsg(`${uploaded} arquivo(s) preservado(s); ${inspected} inspecionado(s); ${imported} importado(s) automaticamente; ${review} aguardando parser/revisão.`,'ok');await loadAll()}
function setUploadMsg(msg,kind){q('uploadMsg').className='msg'+(kind?' '+kind:'');q('uploadMsg').textContent=msg}
q('uploadBtn').addEventListener('click',uploadFiles);

async function fetchRows(table,query){let x=sb.from(table).select('*');for(const op of query||[])x=x[op.method](...op.args);return x}
async function loadAll(){q('syncState').textContent='sincronizando';const calls={
 workouts:fetchRows('health_workouts',[{method:'order',args:['workout_date',{ascending:false}]}]),
 body:fetchRows('health_body_composition',[{method:'order',args:['measured_at',{ascending:false}]}]),
 labs:fetchRows('health_lab_results',[{method:'order',args:['collection_date',{ascending:false}]}]),
 docs:fetchRows('health_documents',[{method:'order',args:['document_date',{ascending:false}]}]),
 exercises:fetchRows('health_workout_exercises',[{method:'order',args:['workout_date',{ascending:false}]},{method:'order',args:['order_index',{ascending:true}]}]),
 sets:fetchRows('health_workout_sets',[{method:'order',args:['workout_date',{ascending:false}]},{method:'order',args:['exercise_order',{ascending:true}]},{method:'order',args:['set_index',{ascending:true}]}]),
 segmental:fetchRows('health_segmental_composition',[{method:'order',args:['measured_at',{ascending:false}]}]),
 requests:fetchRows('health_data_requests',[{method:'order',args:['priority',{ascending:false}]}]),
 plans:fetchRows('health_workout_plans',[{method:'order',args:['plan_date',{ascending:false}]}]),
 insights:fetchRows('health_insights',[{method:'order',args:['generated_at',{ascending:false}]},{method:'limit',args:[30]}]),
 predictions:fetchRows('health_predictions',[{method:'order',args:['generated_at',{ascending:false}]},{method:'limit',args:[20]}]),
 nutrition:fetchRows('health_daily_nutrition',[{method:'order',args:['nutrition_date',{ascending:false}]},{method:'limit',args:[240]}]),
 metrics:fetchRows('health_metrics',[{method:'order',args:['measured_at',{ascending:false}]},{method:'limit',args:[500]}]),
 uploads:fetchRows('health_uploads',[{method:'order',args:['created_at',{ascending:false}]},{method:'limit',args:[80]}]),
 previews:fetchRows('health_ingestion_previews',[{method:'order',args:['created_at',{ascending:false}]},{method:'limit',args:[80]}]),
 quality:fetchRows('health_data_quality_issues',[{method:'order',args:['detected_at',{ascending:false}]},{method:'limit',args:[200]}])
 };
 const entries=await Promise.all(Object.entries(calls).map(async([k,p])=>{try{const r=await p;return[k,r.data||[],r.error]}catch(e){return[k,[],e]}}));state={};const errors=[];for(const [k,data,error] of entries){state[k]=data;if(error)errors.push(`${k}: ${error.message||error}`)}state.canonicalWorkouts=(state.workouts||[]).filter(x=>x.is_canonical!==false&&x.record_status!=='quarantined');state.quarantined=(state.workouts||[]).filter(x=>x.is_canonical===false||x.record_status==='quarantined');renderAll(errors);q('syncState').textContent='atualizado agora'}

function renderAll(errors){const w=state.canonicalWorkouts,b=state.body,l=state.labs,d=state.docs,e=state.exercises,s=state.sets,seg=state.segmental,r=state.requests,p=state.plans,nut=state.nutrition,metrics=state.metrics,quality=state.quality;
 q('systemNotice').className='notice '+(errors.length?'errorBanner':'info');q('systemNotice').textContent=errors.length?'Algumas fontes não carregaram. O app não preenche lacunas por inferência. '+errors.join(' · '):'Histórico canônico carregado com proveniência preservada. Quarentenas e lacunas ficam explícitas; insights só usam evidência disponível.';
 q('kWorkout').textContent=w.length;q('kSets').textContent=s.length;q('kExercises').textContent=e.length;q('kBody').textContent=b.length;q('kLabs').textContent=l.length;
 q('headline').textContent=s.length===137?'Paridade de treino estruturado confirmada: 137 séries.':'Treino estruturado carregado; paridade ainda requer revisão.';
 q('subheadline').textContent=`${w.length} treinos canônicos, ${e.length} exercícios, ${s.length} séries, ${b.length} registros corporais e ${l.length} resultados laboratoriais.`;
 const openQ=quality.filter(x=>String(x.status).toLowerCase()==='open');q('qualityCount').textContent=openQ.length;q('quarantineCount').textContent=state.quarantined.length;
 const pending=r.filter(x=>!['completed'].includes(String(x.status).toLowerCase()));const next=pending[0];q('nextData').textContent=next?.source_name||'Cobertura principal em dia';q('nextDataWhy').textContent=next?.notes||'Nenhum pedido prioritário pendente.';
 renderStatus(w,e,s,nut,metrics,l,openQ);renderRecent(w);renderRequests(pending);renderTimeline(w,b,l,d,p,nut,metrics);renderEvolution(b,seg);renderTraining(w,e,s,p);renderHealth(l,d,metrics,quality);renderNutrition(nut);renderInsights(w,s,b,l,nut,metrics);renderInbox(state.uploads,state.previews,r,quality);renderReadiness(w,s,b,l,nut,metrics)
}
function renderStatus(w,e,s,nut,metrics,l,openQ){const sleep=metrics.filter(x=>x.metric_type==='sleep_duration_h'),activity=metrics.filter(x=>['active_energy_kcal','exercise_minutes','stand_hours'].includes(x.metric_type));const labDates=new Set(l.map(x=>x.collection_date).filter(Boolean));q('statusTraining').innerHTML=`<span class="pill ${s.length===137?'ok':'warn'}">${s.length===137?'paridade':'revisar'}</span><div class="statusValue">${s.length}</div><small>${e.length} exercícios estruturados em ${new Set(s.map(x=>String(x.workout_date).slice(0,10))).size} sessões detalhadas.</small>`;q('statusNutrition').innerHTML=`<span class="pill ${nut.length?'ok':'warn'}">${nut.length?'conectado':'pendente'}</span><div class="statusValue">${nut.length}</div><small>${nut.length?'dias nutricionais importados de fonte real.':'Nenhum dia nutricional importado; sem estimativas.'}</small>`;q('statusRecovery').innerHTML=`<span class="pill ${sleep.length&&activity.length?'ok':'warn'}">${sleep.length&&activity.length?'dados reais':'pendente'}</span><div class="statusValue">${sleep.length}</div><small>${sleep.length} dias/linhas de sono e ${activity.length} métricas de atividade suportadas.</small>`;q('statusLabs').innerHTML=`<span class="pill ${labDates.size>1?'ok':'warn'}">${labDates.size>1?'longitudinal':'limitado'}</span><div class="statusValue">${labDates.size}</div><small>${l.length} resultados estruturados em ${labDates.size} data(s) de coleta.</small>`;q('statusQuality').innerHTML=`<span class="pill ${openQ.length?'warn':'ok'}">auditoria</span><div class="statusValue">${openQ.length}</div><small>questões abertas preservadas, sem resolução automática sem evidência.</small>`}
function renderRecent(w){q('recentWorkouts').innerHTML=w.length?w.slice(0,6).map(x=>`<div class="row"><div><b>${fmtDate(x.workout_date)} · ${esc(x.workout_type)}</b><small>${esc(x.location||'Local não informado')}</small></div><span class="pill ok">canônico</span></div>`).join(''):empty()}
function renderRequests(a){q('topRequests').innerHTML=a.length?a.slice(0,5).map(x=>`<div class="row"><div><b>${esc(x.source_name||x.domain)}</b><small>${esc(x.notes||'')}</small></div><span class="pill warn">P${esc(x.priority??'—')}</span></div>`).join(''):empty('Nenhuma fonte prioritária pendente.')}
function timelineEvents(w,b,l,d,p,nut,metrics){const out=[];w.forEach(x=>out.push({date:x.workout_date,type:'Treino',title:x.workout_type,sub:x.location||'',source:x.source||''}));b.forEach(x=>out.push({date:x.measured_at,type:'Composição',title:`${fmtNum(x.weight_kg)} kg`,sub:x.body_fat_pct!=null?`${fmtNum(x.body_fat_pct)}% gordura registrada`:x.source||'',source:x.source_file||x.source||''}));const labGroups={};l.forEach(x=>{if(x.collection_date)(labGroups[x.collection_date]??=[]).push(x)});Object.entries(labGroups).forEach(([date,a])=>out.push({date,type:'Exames',title:`${a.length} biomarcadores estruturados`,sub:'Coleção laboratorial preservada',source:a[0]?.source_file||a[0]?.source||''}));d.forEach(x=>out.push({date:x.document_date,type:'Documento',title:x.title,sub:x.document_type||'',source:x.source_file||x.source||''}));p.forEach(x=>out.push({date:x.plan_date,type:'Plano',title:x.title,sub:x.status||'',source:x.source_file||x.source||''}));nut.forEach(x=>out.push({date:x.nutrition_date,type:'Nutrição',title:x.calories_kcal!=null?`${fmtNum(x.calories_kcal,0)} kcal registradas`:'Dia nutricional',sub:[x.protein_g!=null?`P ${fmtNum(x.protein_g)}g`:null,x.carbs_g!=null?`C ${fmtNum(x.carbs_g)}g`:null,x.fat_g!=null?`G ${fmtNum(x.fat_g)}g`:null].filter(Boolean).join(' · '),source:x.source_file||x.source||''}));metrics.filter(x=>['sleep_duration_h','steps','active_energy_kcal','exercise_minutes'].includes(x.metric_type)).slice(0,160).forEach(x=>out.push({date:x.measured_at,type:'Métrica',title:`${x.metric_type}: ${fmtNum(x.value)} ${x.unit||''}`,sub:'Registro de atividade/sono',source:x.source_file||x.source||''}));return out.filter(x=>x.date).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function renderTimeline(...a){const ev=timelineEvents(...a);q('timelineList').innerHTML=ev.length?ev.slice(0,240).map(x=>`<div class="timelineItem"><div class="dateBox">${fmtDate(x.date)}</div><div><span class="sourceTag">${esc(x.type)}</span><b>${esc(x.title||'Registro')}</b><small>${esc(x.sub||'')}${x.source?` · fonte: ${esc(x.source)}`:''}</small></div></div>`).join(''):empty('Timeline vazia.')}
function spark(values){if(values.length<2)return'';const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>`<i style="height:${15+((v-min)/range)*48}px" title="${esc(v)}"></i>`).join('')}
function renderEvolution(b,seg){const asc=[...b].sort((a,c)=>String(a.measured_at).localeCompare(String(c.measured_at))),vals=asc.map(x=>Number(x.weight_kg)).filter(Number.isFinite),last=b[0],first=asc[0];q('evoWeight').textContent=last?.weight_kg!=null?`${fmtNum(last.weight_kg)} kg`:'—';q('evoCount').textContent=b.length;q('weightSpark').innerHTML=spark(vals);q('bodyDelta').textContent=first?.weight_kg!=null&&last?.weight_kg!=null?`${fmtNum(Number(last.weight_kg)-Number(first.weight_kg))} kg`:'—';q('bodyList').innerHTML=b.length?b.slice(0,40).map(x=>`<div class="row"><div><b>${fmtDate(x.measured_at)}</b><small>${x.weight_kg!=null?`${fmtNum(x.weight_kg)} kg`:''}${x.skeletal_muscle_mass_kg!=null?` · massa muscular ${fmtNum(x.skeletal_muscle_mass_kg)} kg`:''}${x.body_fat_pct!=null?` · gordura ${fmtNum(x.body_fat_pct)}%`:''}</small></div><span class="sourceTag">${esc(x.source||'fonte')}</span></div>`).join(''):empty();const z=seg[0];q('segmentLatest').innerHTML=z?`<b>${fmtDate(z.measured_at)}</b><div class="mut" style="font-size:11px;margin-top:7px;line-height:1.5">Braço D ${fmtNum(z.lean_right_arm_kg)} kg · Braço E ${fmtNum(z.lean_left_arm_kg)} kg<br>Tronco ${fmtNum(z.lean_trunk_kg)} kg<br>Perna D ${fmtNum(z.lean_right_leg_kg)} kg · Perna E ${fmtNum(z.lean_left_leg_kg)} kg</div>`:empty('Sem análise segmental.')}
function renderTraining(w,e,s,p){q('trainingList').innerHTML=w.length?w.slice(0,55).map(x=>{const ex=e.filter(y=>y.workout_source_record_id===x.source_record_id),sets=s.filter(y=>y.workout_source_record_id===x.source_record_id);return`<details class="workout"><summary><div><b>${fmtDate(x.workout_date)} · ${esc(x.workout_type)}</b><small>${esc(x.location||'')} · ${ex.length} exercícios · ${sets.length} séries${x.duration_minutes?` · ${fmtNum(x.duration_minutes,0)} min`:''}</small></div><span class="pill ok">canônico</span></summary><div class="workoutBody">${ex.length?ex.map(a=>{const ss=sets.filter(z=>z.exercise_source_record_id===a.source_record_id);return`<div class="exercise"><b>${esc(a.exercise)}</b><small>${esc(a.muscle_group||'')}${a.machine?` · ${esc(a.machine)}`:''}</small><div class="setTags">${ss.map(t=>`<span>#${esc(t.set_index)} · ${t.weight!=null?`${fmtNum(t.weight)} ${esc(t.weight_unit||'')}`:'carga —'} · ${esc(t.reps_raw||t.reps_numeric||'reps —')}${t.technique?` · ${esc(t.technique)}`:''}${t.failure?' · falha':''}</span>`).join('')}</div></div>`}).join(''):`<div class="mut">Detalhe estruturado ainda não disponível; texto bruto foi preservado.</div>`}</div>`}).join(''):empty();q('planList').innerHTML=p.length?p.map(x=>`<div class="row"><div><b>${fmtDate(x.plan_date)} · ${esc(x.title)}</b><small>${esc(x.planned_content||'')}${x.location?` · ${esc(x.location)}`:''}</small></div><span class="pill ${statusPill(x.status)}">${esc(x.status||'plano')}</span></div>`).join(''):empty('Nenhum plano preservado.')}
function renderHealth(l,d,metrics,quality){q('labList').innerHTML=l.length?l.slice(0,90).map(x=>`<div class="row"><div><b>${esc(x.biomarker)}</b><small>${fmtDate(x.collection_date)} · ${esc(x.result_raw)}${x.reference_range?` · ref. ${esc(x.reference_range)}`:''}${x.laboratory?` · ${esc(x.laboratory)}`:''}</small></div>${x.flag?`<span class="pill warn">${esc(x.flag)}</span>`:''}</div>`).join(''):empty();q('docList').innerHTML=d.length?d.slice(0,55).map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${fmtDate(x.document_date)} · ${esc(x.document_type||'documento')} · ${esc(x.source_file||x.source||'fonte registrada')}</small></div><span class="pill ${statusPill(x.extraction_status)}">${esc(x.extraction_status||'inventário')}</span></div>`).join(''):empty();const mm=metrics.filter(x=>['steps','active_energy_kcal','exercise_minutes','stand_hours','sleep_duration_h','resting_heart_rate_bpm','heart_rate_bpm'].includes(x.metric_type));q('metricList').innerHTML=mm.length?mm.slice(0,80).map(x=>`<div class="row"><div><b>${esc(x.metric_type)}</b><small>${fmtDate(x.measured_at)} · ${fmtNum(x.value)} ${esc(x.unit||'')} · ${esc(x.source||'fonte')}</small></div></div>`).join(''):empty('Atividade/sono ainda não importados.');const open=quality.filter(x=>String(x.status).toLowerCase()==='open');q('healthQuality').innerHTML=open.length?open.slice(0,30).map(x=>`<div class="row"><div><b>${esc(x.issue_code)}</b><small>${esc(x.description)}</small></div><span class="pill warn">${esc(x.severity)}</span></div>`).join(''):empty('Nenhuma questão aberta.')}
function renderNutrition(n){if(!n.length){q('nutritionTitle').textContent='Sem dados nutricionais reais importados';q('nutritionText').textContent='A estrutura está pronta para MyFitnessPal. Metas conhecidas não são usadas para fabricar ingestão histórica.';q('nutritionList').innerHTML=empty('Envie o export do MyFitnessPal em Dados / Inbox.');return}q('nutritionTitle').textContent=`${n.length} dias nutricionais recentes carregados`;q('nutritionText').textContent='Somente valores presentes na fonte são exibidos; campos ausentes permanecem vazios.';q('nutritionList').innerHTML=n.map(x=>`<div class="row"><div><b>${fmtDate(x.nutrition_date)}${x.calories_kcal!=null?` · ${fmtNum(x.calories_kcal,0)} kcal`:''}</b><small>${[x.protein_g!=null?`Proteína ${fmtNum(x.protein_g)}g`:null,x.carbs_g!=null?`Carboidrato ${fmtNum(x.carbs_g)}g`:null,x.fat_g!=null?`Gordura ${fmtNum(x.fat_g)}g`:null,x.fiber_g!=null?`Fibra ${fmtNum(x.fiber_g)}g`:null,x.water_ml!=null?`Água ${fmtNum(x.water_ml,0)} ml`:null].filter(Boolean).join(' · ')}</small></div><span class="sourceTag">${esc(x.source||'fonte')}</span></div>`).join('')}
function renderInsights(w,s,b,l,nut,metrics){const cards=[];if(w.length)cards.push({t:'Treino',v:`${w.length} sessões canônicas`,x:`${s.length} séries estruturadas; análise baseada apenas no histórico registrado.`});if(b.length)cards.push({t:'Composição',v:`${b.length} medições`,x:`Série de ${fmtDate([...b].sort((a,c)=>String(a.measured_at).localeCompare(String(c.measured_at)))[0]?.measured_at)} a ${fmtDate(b[0]?.measured_at)}.`});if(l.length)cards.push({t:'Laboratório',v:`${new Set(l.map(x=>x.collection_date)).size} coleta(s)`,x:`${l.length} biomarcadores estruturados. Longitudinalidade limitada enquanto houver uma única coleta completa.`});if(nut.length)cards.push({t:'Nutrição',v:`${nut.length} dias carregados`,x:'Correlação com treino só deve ser calculada para datas com ingestão real.'});const sleep=metrics.filter(x=>x.metric_type==='sleep_duration_h');if(sleep.length)cards.push({t:'Sono',v:`${sleep.length} registros`,x:'Base observacional disponível para futuras correlações, sem inferência clínica.'});q('insightGrid').innerHTML=cards.length?cards.map(x=>`<div class="insight"><b>${esc(x.t)}</b><strong>${esc(x.v)}</strong><small>${esc(x.x)}</small></div>`).join(''):empty();q('persistedInsights').innerHTML=(state.insights||[]).length?(state.insights||[]).slice(0,20).map(x=>`<div class="row"><div><b>${esc(x.title||x.insight_type)}</b><small>${esc(x.summary||x.details||'')} · ${fmtDate(x.period_end||x.generated_at)}</small></div><span class="pill ${statusPill(x.status)}">${esc(x.status||x.confidence||'evidência')}</span></div>`).join(''):empty('Nenhum insight persistido adicional.')}
function renderReadiness(w,s,b,l,nut,metrics){const checks=[['Treino estruturado',s.length===137,`${s.length}/137 séries`],['Composição longitudinal',b.length>=8,`${b.length} medições`],['Nutrição real',nut.length>=30,`${nut.length} dias carregados`],['Atividade',metrics.some(x=>['steps','exercise_minutes','active_energy_kcal'].includes(x.metric_type)),`${metrics.filter(x=>['steps','exercise_minutes','active_energy_kcal'].includes(x.metric_type)).length} registros`],['Sono',metrics.filter(x=>x.metric_type==='sleep_duration_h').length>=14,`${metrics.filter(x=>x.metric_type==='sleep_duration_h').length} registros`],['Labs longitudinais',new Set(l.map(x=>x.collection_date)).size>=2,`${new Set(l.map(x=>x.collection_date)).size} coleta(s)`]];const ok=checks.filter(x=>x[1]).length;q('predictionReadiness').textContent=`${ok}/${checks.length} fundamentos disponíveis`;q('readinessGrid').innerHTML=checks.map(x=>`<div class="ready"><i class="${x[1]?'yes':'no'}"></i><div><b>${esc(x[0])}</b><small>${esc(x[2])}</small></div></div>`).join('');q('predictionStatus').textContent=ok===checks.length?'A base cobre todos os fundamentos técnicos mínimos; qualquer previsão futura ainda deve ser validada e apresentada com incerteza.':'Prediction readiness incompleta. O app não gera números preditivos para preencher os domínios ausentes.'}
function renderInbox(u,pr,r,quality){q('uploadList').innerHTML=u.length?u.map(x=>{const p=pr.find(y=>y.upload_id===x.id);return`<div class="row"><div><b>${esc(x.original_filename)}</b><small>${esc(x.source_type)} · ${fmtDate(x.created_at)}${p?` · ${esc(p.detected_format||'formato')} · ${esc(p.row_count??'—')} registros inspecionados`:''}</small></div><span class="pill ${statusPill(x.status)}">${esc(x.status)}</span></div>`}).join(''):empty('Nenhum upload recebido ainda.');const complete=r.filter(x=>String(x.status).toLowerCase()==='completed').length,total=r.length,pct=total?Math.round(complete/total*100):0;q('coverageBar').style.width=pct+'%';q('coverageLabel').textContent=`${complete}/${total} solicitações de cobertura concluídas`;q('requestList').innerHTML=r.length?r.map(x=>`<div class="row"><div><b>${esc(x.source_name||x.domain)}</b><small>${esc(x.notes||'')}</small></div><span class="pill ${String(x.status).toLowerCase()==='completed'?'ok':'warn'}">${esc(x.status)}</span></div>`).join(''):empty();q('qualityList').innerHTML=quality.length?quality.map(x=>`<div class="row"><div><b>${esc(x.issue_code)}</b><small>${esc(x.description)}${x.resolution_notes?` · resolução: ${esc(x.resolution_notes)}`:''}</small></div><span class="pill ${String(x.status).toLowerCase()==='open'?'warn':'ok'}">${esc(x.status)}</span></div>`).join(''):empty()}

sb.auth.getSession().then(({data})=>setView(data.session));sb.auth.onAuthStateChange((_e,s)=>setView(s));
