const SUPABASE_URL='https://tadhkamnwtsbdozwkyut.supabase.co';
const SUPABASE_KEY='sb_publishable__p3SAbpThUIKtDr7A4llPw_AVkOaNkm';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const q=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return'—';const s=String(v).slice(0,10),[y,m,d]=s.split('-');return y&&m&&d?`${d}/${m}/${y}`:s};
const fmtNum=(v,d=1)=>v==null||v===''?'—':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const daysAgo=v=>{if(!v)return null;const t=new Date(String(v).slice(0,10)+'T12:00:00').getTime();return Number.isFinite(t)?Math.floor((Date.now()-t)/86400000):null};
const empty=msg=>`<div class="empty">${esc(msg||'Nenhum registro disponível.')}</div>`;
const statusPill=s=>{const x=String(s||'').toLowerCase();return x==='completed'||x==='imported'||x==='validated'||x==='active'?'ok':x==='rejected'||x==='failed'||x==='quarantined'?'bad':'warn'};
let currentSession=null;
let state={};

function setView(session){currentSession=session;q('loginView').classList.toggle('hidden',!!session);q('app').classList.toggle('hidden',!session);if(session)loadAll()}
async function signIn(){q('loginMsg').textContent='Entrando…';const {error}=await sb.auth.signInWithPassword({email:q('email').value.trim(),password:q('password').value});q('loginMsg').textContent=error?error.message:''}
async function signOut(){await sb.auth.signOut()}
q('loginBtn').addEventListener('click',signIn);q('password').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});q('logoutBtn').addEventListener('click',signOut);

function activateTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));q(tab)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));
q('moreBtn')?.addEventListener('click',()=>activateTab('inbox'));

function safeName(name){return String(name||'arquivo').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-120)}
const sourceGuides={
 myfitnesspal:{title:'MyFitnessPal',what:'Envie CSV ou ZIP exportado. O parser agrega somente valores presentes no arquivo; macros ausentes não são estimados.',accept:['csv','zip','json']},
 lab:{title:'Exames históricos',what:'Envie PDF, imagem ou arquivo estruturado. O original fica preservado; biomarcadores só entram como estruturados com evidência suficiente.',accept:['pdf','jpg','jpeg','png','heic','csv','json']},
 apple_health:{title:'Apple Health',what:'Envie o ZIP de exportação ou export.xml. Atividade diária e sono suportado podem ser normalizados; passos sobrepostos entre dispositivos não são somados automaticamente.',accept:['zip','xml']},
 polar:{title:'Polar',what:'Envie CSV ou JSON exportado. Nesta fase o arquivo é inspecionado e preservado para parser especializado, sem completar métricas ausentes.',accept:['csv','json','zip']},
 body_composition:{title:'Bioimpedância',what:'Envie PDF, imagem, CSV ou JSON. O arquivo bruto permanece ligado à proveniência.',accept:['pdf','jpg','jpeg','png','heic','csv','json']},
 training:{title:'Treino',what:'Envie fonte estruturada ou documento bruto. Nenhuma carga ou repetição é convertida quando a unidade não está explícita.',accept:['csv','json','pdf','jpg','jpeg','png']},
 document:{title:'Outro documento',what:'O arquivo é preservado como evidência. Extração automática só ocorre quando houver parser validado para o formato.',accept:['pdf','jpg','jpeg','png','heic','csv','json','zip','xml']}
};
function ext(name){return String(name||'').toLowerCase().split('.').pop()||''}
function updateUploadGuide(){const g=sourceGuides[q('uploadType').value];q('uploadGuideTitle').textContent=g.title;q('uploadGuideText').textContent=g.what;q('uploadGuideFormats').textContent='Formatos esperados: '+g.accept.join(', ').toUpperCase()}
q('uploadType').addEventListener('change',updateUploadGuide);updateUploadGuide();

async function uploadFiles(){const files=[...(q('uploadFile').files||[])];if(!currentSession?.user||!files.length){setUploadMsg('Selecione pelo menos um arquivo.','bad');return}const guide=sourceGuides[q('uploadType').value];for(const file of files){if(file.size>50*1024*1024){setUploadMsg(`${file.name}: limite de 50 MB excedido.`,'bad');return}if(!guide.accept.includes(ext(file.name))){setUploadMsg(`${file.name}: formato não esperado para ${guide.title}.`,'bad');return}}
 q('uploadBtn').disabled=true;setUploadMsg('Enviando para armazenamento privado e inspecionando…','');let uploaded=0,inspected=0,imported=0,review=0;
 for(const file of files){const path=`${currentSession.user.id}/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${safeName(file.name)}`;const up=await sb.storage.from('health-inbox').upload(path,file,{upsert:false,contentType:file.type||undefined});if(up.error){setUploadMsg(`Falha em ${file.name}: ${up.error.message}`,'bad');continue}
  const meta=await sb.from('health_uploads').insert({user_id:currentSession.user.id,source_type:q('uploadType').value,original_filename:file.name,storage_path:path,mime_type:file.type||null,size_bytes:file.size,status:'uploaded',notes:'Recebido pelo Health Data Inbox v7'}).select().single();
  if(meta.error||!meta.data){await sb.storage.from('health-inbox').remove([path]);setUploadMsg(`Registro de ${file.name} falhou: ${meta.error?.message||'erro desconhecido'}`,'bad');continue}
  uploaded++;const inspect=await sb.functions.invoke('health-inspect-upload',{body:{upload_id:meta.data.id}});if(!inspect.error&&inspect.data?.ok){inspected++;if(inspect.data.upload_status==='imported')imported++;if(inspect.data.upload_status==='review_required')review++}else if(inspect.error){setUploadMsg(`${file.name} foi preservado, mas a inspeção falhou: ${inspect.error.message}`,'bad')}
 }
 q('uploadBtn').disabled=false;q('uploadFile').value='';if(uploaded)setUploadMsg(`${uploaded} arquivo(s) preservado(s); ${inspected} inspecionado(s); ${imported} importado(s) automaticamente; ${review} aguardando parser/revisão.`,'ok');await loadAll()}
function setUploadMsg(msg,kind){q('uploadMsg').className='msg'+(kind?' '+kind:'');q('uploadMsg').textContent=msg}
q('uploadBtn').addEventListener('click',uploadFiles);

async function fetchRows(table,query){let x=sb.from(table).select('*');for(const op of query||[])x=x[op.method](...op.args);return x}
async function loadAll(){q('syncState').textContent='sincronizando';const calls={
 workouts:fetchRows('health_workouts',[{method:'order',args:['workout_date',{ascending:false}]}]),
 body:fetchRows('health_body_composition',[{method:'order',args:['measured_at',{ascending:false}]}]),
 labs:fetchRows('health_lab_results',[{method:'order',args:['collection_date',{ascending:false}]}]),
 docs:fetchRows('health_documents',[{method:'order',args:['document_date',{ascending:false}]}]),
 exercises:fetchRows('health_workout_exercises',[{method:'order',args:['workout_date',{ascending:false}]},{method:'order',args:['order_index',{ascending:true}]}]),
 sets:fetchRows('health_workout_sets',[{method:'order',args:['workout_date',{ascending:false}]},{method:'order',args:['exercise_order',{ascending:true}]},{method:'order',args:['set_index',{ascending:true}]}]),
 segmental:fetchRows('health_segmental_composition',[{method:'order',args:['measured_at',{ascending:false}]}]),
 requests:fetchRows('health_data_requests',[{method:'order',args:['priority',{ascending:false}]}]),
 plans:fetchRows('health_workout_plans',[{method:'order',args:['plan_date',{ascending:false}]}]),
 insights:fetchRows('health_insights',[{method:'order',args:['generated_at',{ascending:false}]},{method:'limit',args:[30]}]),
 predictions:fetchRows('health_predictions',[{method:'order',args:['generated_at',{ascending:false}]},{method:'limit',args:[20]}]),
 nutrition:fetchRows('health_daily_nutrition',[{method:'order',args:['nutrition_date',{ascending:false}]},{method:'limit',args:[240]}]),
 metrics:fetchRows('health_metrics',[{method:'order',args:['measured_at',{ascending:false}]},{method:'limit',args:[500]}]),
 uploads:fetchRows('health_uploads',[{method:'order',args:['created_at',{ascending:false}]},{method:'limit',args:[80]}]),
 previews:fetchRows('health_ingestion_previews',[{method:'order',args:['created_at',{ascending:false}]},{method:'limit',args:[80]}]),
 quality:fetchRows('health_data_quality_issues',[{method:'order',args:['detected_at',{ascending:false}]},{method:'limit',args:[200]}])
 };
 const entries=await Promise.all(Object.entries(calls).map(async([k,p])=>{try{const r=await p;return[k,r.data||[],r.error]}catch(e){return[k,[],e]}}));state={};const errors=[];for(const [k,data,error] of entries){state[k]=data;if(error)errors.push(`${k}: ${error.message||error}`)}state.canonicalWorkouts=(state.workouts||[]).filter(x=>x.is_canonical!==false&&x.record_status!=='quarantined');state.quarantined=(state.workouts||[]).filter(x=>x.is_canonical===false||x.record_status==='quarantined');renderAll(errors);q('syncState').textContent='atualizado agora'}

function renderAll(errors){const w=state.canonicalWorkouts,b=state.body,l=state.labs,d=state.docs,e=state.exercises,s=state.sets,seg=state.segmental,r=state.requests,p=state.plans,nut=state.nutrition,metrics=state.metrics,quality=state.quality;
 q('systemNotice').className='notice '+(errors.length?'errorBanner':'info');q('systemNotice').textContent=errors.length?'Algumas fontes não carregaram. O app não preenche lacunas por inferência. '+errors.join(' · '):'Histórico canônico carregado com proveniência preservada. Quarentenas e lacunas ficam explícitas; insights só usam evidência disponível.';
 q('kWorkout').textContent=w.length;q('kSets').textContent=s.length;q('kExercises').textContent=e.length;q('kBody').textContent=b.length;q('kLabs').textContent=l.length;
 q('headline').textContent=s.length===137?'Paridade de treino estruturado confirmada: 137 séries.':'Treino estruturado carregado; paridade ainda requer revisão.';
 q('subheadline').textContent=`${w.length} treinos canônicos, ${e.length} exercícios, ${s.length} séries, ${b.length} registros corporais e ${l.length} resultados laboratoriais.`;
 const openQ=quality.filter(x=>String(x.status).toLowerCase()==='open');q('qualityCount').textContent=openQ.length;q('quarantineCount').textContent=state.quarantined.length;
 const pending=r.filter(x=>!['completed'].includes(String(x.status).toLowerCase()));const next=pending[0];q('nextData').textContent=next?.source_name||'Cobertura principal em dia';q('nextDataWhy').textContent=next?.notes||'Nenhum pedido prioritário pendente.';
 renderStatus(w,e,s,nut,metrics,l,openQ);renderRecent(w);renderRequests(pending);renderTimeline(w,b,l,d,p,nut,metrics);renderEvolution(b,seg);renderTraining(w,e,s,p);renderHealth(l,d,metrics,quality);renderNutrition(nut);renderInsights(w,s,b,l,nut,metrics);renderInbox(state.uploads,state.previews,r,quality);renderReadiness(w,s,b,l,nut,metrics)
}
function renderStatus(w,e,s,nut,metrics,l,openQ){const sleep=metrics.filter(x=>x.metric_type==='sleep_duration_h'),activity=metrics.filter(x=>['active_energy_kcal','exercise_minutes','stand_hours'].includes(x.metric_type));const labDates=new Set(l.map(x=>x.collection_date).filter(Boolean));q('statusTraining').innerHTML=`<span class="pill ${s.length===137?'ok':'warn'}">${s.length===137?'paridade':'revisar'}</span><div class="statusValue">${s.length}</div><small>${e.length} exercícios estruturados em ${new Set(s.map(x=>String(x.workout_date).slice(0,10))).size} sessões detalhadas.</small>`;q('statusNutrition').innerHTML=`<span class="pill ${nut.length?'ok':'warn'}">${nut.length?'conectado':'pendente'}</span><div class="statusValue">${nut.length}</div><small>${nut.length?'dias nutricionais importados de fonte real.':'Nenhum dia nutricional importado; sem estimativas.'}</small>`;q('statusRecovery').innerHTML=`<span class="pill ${sleep.length&&activity.length?'ok':'warn'}">${sleep.length&&activity.length?'dados reais':'pendente'}</span><div class="statusValue">${sleep.length}</div><small>${sleep.length} dias/linhas de sono e ${activity.length} métricas de atividade suportadas.</small>`;q('statusLabs').innerHTML=`<span class="pill ${labDates.size>1?'ok':'warn'}">${labDates.size>1?'longitudinal':'limitado'}</span><div class="statusValue">${labDates.size}</div><small>${l.length} resultados estruturados em ${labDates.size} data(s) de coleta.</small>`;q('statusQuality').innerHTML=`<span class="pill ${openQ.length?'warn':'ok'}">auditoria</span><div class="statusValue">${openQ.length}</div><small>questões abertas preservadas, sem resolução automática sem evidência.</small>`}
function renderRecent(w){q('recentWorkouts').innerHTML=w.length?w.slice(0,6).map(x=>`<div class="row"><div><b>${fmtDate(x.workout_date)} · ${esc(x.workout_type)}</b><small>${esc(x.location||'Local não informado')}</small></div><span class="pill ok">canônico</span></div>`).join(''):empty()}
function renderRequests(a){q('topRequests').innerHTML=a.length?a.slice(0,5).map(x=>`<div class="row"><div><b>${esc(x.source_name||x.domain)}</b><small>${esc(x.notes||'')}</small></div><span class="pill warn">P${esc(x.priority??'—')}</span></div>`).join(''):empty('Nenhuma fonte prioritária pendente.')}
function timelineEvents(w,b,l,d,p,nut,metrics){const out=[];w.forEach(x=>out.push({date:x.workout_date,type:'Treino',title:x.workout_type,sub:x.location||'',source:x.source||''}));b.forEach(x=>out.push({date:x.measured_at,type:'Composição',title:`${fmtNum(x.weight_kg)} kg`,sub:x.body_fat_pct!=null?`${fmtNum(x.body_fat_pct)}% gordura registrada`:x.source||'',source:x.source_file||x.source||''}));const labGroups={};l.forEach(x=>{if(x.collection_date)(labGroups[x.collection_date]??=[]).push(x)});Object.entries(labGroups).forEach(([date,a])=>out.push({date,type:'Exames',title:`${a.length} biomarcadores estruturados`,sub:'coleta laboratorial',source:a[0]?.source_file||''}));d.forEach(x=>out.push({date:x.document_date,type:'Documento',title:x.title,sub:x.document_type||'',source:x.source_file||''}));p.forEach(x=>out.push({date:x.plan_date,type:'Plano',title:x.title,sub:x.location||'',source:x.source_file||''}));nut.forEach(x=>out.push({date:x.nutrition_date,type:'Nutrição',title:x.calories_kcal!=null?`${fmtNum(x.calories_kcal,0)} kcal registradas`:'Dia nutricional',sub:x.protein_g!=null?`proteína ${fmtNum(x.protein_g,0)} g`:x.source||'',source:x.source_file||''}));const mg={};metrics.forEach(x=>{const date=String(x.measured_at||'').slice(0,10);if(date)(mg[date]??=[]).push(x)});Object.entries(mg).slice(0,80).forEach(([date,a])=>{const sleep=a.find(x=>x.metric_type==='sleep_duration_h'),ex=a.find(x=>x.metric_type==='exercise_minutes');out.push({date,type:'Atividade/sono',title:sleep?`Sono registrado: ${fmtNum(sleep.value,1)} h`:'Métricas de atividade',sub:ex?`${fmtNum(ex.value,0)} min de exercício registrados`:`${a.length} métrica(s)`,source:a[0]?.source_file||a[0]?.source||''})});return out.filter(x=>x.date).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,220)}
function renderTimeline(...args){const events=timelineEvents(...args);q('timelineList').innerHTML=events.length?events.map(x=>`<div class="timelineItem"><div class="timelineDate">${fmtDate(x.date)}<div class="timelineMeta"><span class="pill">${esc(x.type)}</span></div></div><div class="timelineBody"><b>${esc(x.title)}</b><small>${esc(x.sub||'')}</small>${x.source?`<div class="sourceTag">fonte: ${esc(x.source)}</div>`:''}</div></div>`).join(''):empty()}
function renderEvolution(body,segment){const latest=body[0],oldest=body[body.length-1];q('evoCount').textContent=body.length;q('evoWeight').textContent=latest?`${fmtNum(latest.weight_kg)} kg`:'—';if(latest&&oldest&&latest.weight_kg!=null&&oldest.weight_kg!=null){const delta=Number(latest.weight_kg)-Number(oldest.weight_kg);q('bodyDelta').textContent=`${delta>0?'+':''}${fmtNum(delta)} kg`}else q('bodyDelta').textContent='—';const vals=body.slice(0,18).reverse().filter(x=>Number.isFinite(Number(x.weight_kg)));if(vals.length){const ns=vals.map(x=>Number(x.weight_kg)),min=Math.min(...ns),max=Math.max(...ns),span=Math.max(max-min,1);q('weightSpark').innerHTML=vals.map((x,i)=>`<i style="height:${24+((Number(x.weight_kg)-min)/span)*58}px" title="${fmtDate(x.measured_at)} · ${fmtNum(x.weight_kg)} kg"></i>`).join('')}else q('weightSpark').innerHTML='';q('bodyList').innerHTML=body.length?body.map(x=>`<div class="row"><div><b>${fmtDate(x.measured_at)}</b><small>${esc(x.source||'fonte preservada')}</small><span class="sourceTag">${esc(x.source_file||'')}</span></div><div class="rowRight"><b>${fmtNum(x.weight_kg)} kg</b><small>${x.body_fat_pct!=null?fmtNum(x.body_fat_pct)+'% gordura':''}</small></div></div>`).join(''):empty();const x=segment[0];q('segmentLatest').innerHTML=x?`<b>${fmtDate(x.measured_at)}</b><div class="mut" style="font-size:10px;margin:5px 0 10px">Massa magra segmental · leitura descritiva</div><div class="compactStat"><span>Braço D / E</span><b>${fmtNum(x.lean_right_arm_kg)} / ${fmtNum(x.lean_left_arm_kg)} kg</b></div><div class="compactStat"><span>Perna D / E</span><b>${fmtNum(x.lean_right_leg_kg)} / ${fmtNum(x.lean_left_leg_kg)} kg</b></div><div class="compactStat"><span>Tronco</span><b>${fmtNum(x.lean_trunk_kg)} kg</b></div><div class="sourceTag" style="margin-top:8px">${esc(x.source_file||x.source||'')}</div>`:empty('Sem análise segmental.')}
function renderTraining(workouts,exercises,sets,plans){const exBy={};exercises.forEach(x=>(exBy[x.workout_source_record_id]??=[]).push(x));const setBy={};sets.forEach(x=>(setBy[x.exercise_source_record_id]??=[]).push(x));q('trainingList').innerHTML=workouts.length?workouts.map(x=>{const xs=exBy[x.source_record_id]||[];const setCount=xs.reduce((n,a)=>n+(setBy[a.source_record_id]?.length||0),0);const detail=xs.length?xs.map(a=>{const ss=setBy[a.source_record_id]||[];const conf=String(a.confidence||'').toLowerCase();return `<div class="exercise"><div class="exerciseHeader"><div><b>${esc(a.exercise)}</b><small class="mut">${esc(a.machine||a.muscle_group||'')}</small></div><span class="pill ${conf==='high'?'ok':'warn'}">${esc(a.confidence||'fonte')}</span></div>${ss.length?ss.map(z=>`<div class="setline">S${z.set_index}: ${z.weight!=null?fmtNum(z.weight):'—'} ${esc(z.weight_unit==='plate_index'?'placa':z.weight_unit==='lb_per_side'?'lb/lado':z.weight_unit==='source_value'?'valor fonte':z.weight_unit||'')} × ${esc(z.reps_raw||z.reps_numeric||'—')}${z.failure?' · falha registrada':''}${z.technique?' · '+esc(z.technique):''}</div>`).join(''):`<div class="setline">Sem séries estruturadas para este exercício.</div>`}${a.source_text?`<div class="evidence">Fonte: ${esc(a.source_text)}</div>`:''}</div>`}).join(''):empty('Sessão preservada; detalhe ainda não estruturado.');return `<div class="workout"><div class="workoutHead" role="button" tabindex="0"><div><b>${fmtDate(x.workout_date)} · ${esc(x.workout_type)}</b><small class="mut">${esc(x.location||'Local não informado')}${x.duration_minutes?' · '+fmtNum(x.duration_minutes,0)+' min':''}</small></div><div class="rowRight"><b>${setCount} séries</b><small>${xs.length} exercícios</small></div></div><div class="detail">${detail}</div></div>`}).join(''):empty();q('trainingList').querySelectorAll('.workoutHead').forEach(h=>{const toggle=()=>h.parentElement.classList.toggle('open');h.addEventListener('click',toggle);h.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});q('planList').innerHTML=plans.length?plans.map(x=>`<div class="row"><div><b>${fmtDate(x.plan_date)} · ${esc(x.title)}</b><small>${esc(x.location||'Local não informado')}</small><span class="sourceTag">${esc(x.source_file||x.source||'')}</span></div><span class="pill ${statusPill(x.status)}">${esc(x.status||'plano')}</span></div>`).join(''):empty()}
function renderHealth(labs,docs,metrics,quality){q('labList').innerHTML=labs.length?labs.map(x=>{const f=String(x.flag||'').toLowerCase();return `<div class="row"><div><b>${esc(x.biomarker)}</b><small>${fmtDate(x.collection_date)} · ${esc(x.reference_range||'referência não informada')}</small><span class="sourceTag">${esc(x.source_file||'')}</span></div><div class="rowRight"><b>${esc(x.result_raw)} ${esc(x.unit||'')}</b><span class="pill ${f==='normal'?'ok':f?'warn':''}">${esc(x.flag||'sem flag')}</span></div></div>`}).join(''):empty();q('docList').innerHTML=docs.length?docs.map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${fmtDate(x.document_date)} · ${esc(x.document_type||'documento')}</small><span class="sourceTag">${esc(x.source_file||'')}</span></div><span class="pill ${statusPill(x.extraction_status)}">${esc(x.extraction_status||'inventário')}</span></div>`).join(''):empty();const daily=metrics.slice(0,100);q('metricList').innerHTML=daily.length?daily.map(x=>`<div class="row"><div><b>${fmtDate(x.measured_at)} · ${esc(x.metric_type)}</b><small>${esc(x.source||'fonte preservada')}</small></div><div class="rowRight"><b>${fmtNum(x.value,2)} ${esc(x.unit||'')}</b><small>${esc(x.confidence||'')}</small></div></div>`).join(''):empty('Aguardando Apple Health/Polar para atividade e sono.');const qOpen=quality.filter(x=>String(x.status).toLowerCase()==='open'&&['limited_longitudinal_coverage','missing_data','source_date_conflict_risk','provenance'].includes(String(x.category)));q('healthQuality').innerHTML=qOpen.length?qOpen.slice(0,8).map(x=>`<div class="row qualityOpen"><div><b>${esc(x.issue_code)}</b><small>${esc(x.description)}</small></div><span class="pill warn">aberto</span></div>`).join(''):empty('Sem alertas adicionais nesta visão.')}
function renderNutrition(nut){if(nut.length){q('nutritionTitle').textContent='Nutrição conectada por fonte real';q('nutritionText').textContent='A visualização usa somente valores efetivamente importados; campos ausentes permanecem vazios.';q('nutritionList').innerHTML=nut.map(x=>`<div class="row"><div><b>${fmtDate(x.nutrition_date)}</b><small>${esc(x.source||'fonte nutricional')}</small><span class="sourceTag">${esc(x.source_file||'')}</span></div><div class="rowRight"><b>${x.calories_kcal!=null?fmtNum(x.calories_kcal,0)+' kcal':'—'}</b><small>${[x.protein_g!=null?'P '+fmtNum(x.protein_g,0)+'g':'',x.carbs_g!=null?'C '+fmtNum(x.carbs_g,0)+'g':'',x.fat_g!=null?'G '+fmtNum(x.fat_g,0)+'g':''].filter(Boolean).join(' · ')}</small></div></div>`).join('')}else{q('nutritionTitle').textContent='Sem dados nutricionais reais importados';q('nutritionText').textContent='O próximo passo é um export do MyFitnessPal. O sistema não usa metas ou memória para inventar refeições/macros.';q('nutritionList').innerHTML=empty('Aguardando uma fonte nutricional real.') }}
function evidenceCard(title,body,label='evidência',kind=''){return `<div class="card insight"><h3>${esc(title)}</h3><p>${esc(body)}</p><div style="margin-top:9px"><span class="pill ${kind}">${esc(label)}</span></div></div>`}
function renderInsights(w,sets,body,labs,nut,metrics){const last28=w.filter(x=>{const d=daysAgo(x.workout_date);return d!=null&&d>=0&&d<=28}).length,labDates=new Set(labs.map(x=>x.collection_date).filter(Boolean)),sleep=metrics.filter(x=>x.metric_type==='sleep_duration_h'),activity=metrics.filter(x=>['active_energy_kcal','exercise_minutes','stand_hours'].includes(x.metric_type));const latest=body[0],bodyFresh=latest?daysAgo(latest.measured_at):null;const cards=[evidenceCard('Treino · alta confiança',`${last28} sessões nos últimos 28 dias; ${sets.length} séries estruturadas no histórico detalhado. Recuperação não é inferida sem sono/atividade.`,'fonte canônica','ok'),evidenceCard('Composição · alta confiança',`${body.length} registros corporais${bodyFresh!=null?`; último há ${bodyFresh} dia(s)`:''}. A leitura é descritiva, sem classificar aparência.`,'série histórica','ok'),evidenceCard('Exames · cobertura '+(labDates.size>1?'longitudinal':'limitada'),`${labs.length} resultados em ${labDates.size} data(s) de coleta. Comparações clínicas exigem coletas comparáveis.`,'limitação explícita',labDates.size>1?'ok':'warn'),evidenceCard('Nutrição',nut.length?`${nut.length} dias importados de fonte real.`:'Ainda sem histórico importado; correlações com treino ficam retidas.','sem estimativas',nut.length?'ok':'warn'),evidenceCard('Atividade & sono',sleep.length&&activity.length?`${sleep.length} registros de sono e ${activity.length} métricas de atividade disponíveis.`:'Série ainda ausente ou parcial; nenhum readiness artificial é calculado.','dados observados',sleep.length&&activity.length?'ok':'warn'),evidenceCard('Proveniência','Dado bruto, registro normalizado, insight e previsão ficam separados. Quarentenas não entram nos cálculos canônicos.','governança','ok')];q('insightGrid').innerHTML=cards.join('');const saved=(state.insights||[]).filter(x=>x.status==='active');q('persistedInsights').innerHTML=saved.length?saved.map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${esc(x.summary)}${x.limitations?' · Limitação: '+esc(x.limitations):''}</small></div><span class="pill">${esc(x.confidence_label||'evidência')}</span></div>`).join(''):empty('Nenhum insight persistido adicional.')}
function readinessChecks(w,sets,body,labs,nut,metrics){const labDates=new Set(labs.map(x=>x.collection_date).filter(Boolean)),sleepDays=new Set(metrics.filter(x=>x.metric_type==='sleep_duration_h').map(x=>String(x.measured_at).slice(0,10))),activityDays=new Set(metrics.filter(x=>['active_energy_kcal','exercise_minutes','stand_hours'].includes(x.metric_type)).map(x=>String(x.measured_at).slice(0,10))),nutritionDays=new Set(nut.map(x=>x.nutrition_date).filter(Boolean));return[{name:'Treino estruturado',ok:sets.length>=100,detail:`${sets.length} séries; base estrutural ${sets.length>=100?'suficiente':'ainda curta'}.`},{name:'Composição longitudinal',ok:body.length>=12,detail:`${body.length} registros corporais.`},{name:'Nutrição',ok:nutritionDays.size>=14,detail:`${nutritionDays.size} dia(s) nutricionais; alvo técnico mínimo para correlação = 14.`},{name:'Sono/atividade',ok:sleepDays.size>=14&&activityDays.size>=14,detail:`sono ${sleepDays.size} dia(s); atividade ${activityDays.size} dia(s).`},{name:'Exames longitudinais',ok:labDates.size>=2,detail:`${labDates.size} data(s) de coleta estruturadas.`}]}
function renderReadiness(...args){const checks=readinessChecks(...args),ok=checks.filter(x=>x.ok).length;q('predictionReadiness').textContent=`${ok}/${checks.length} pilares com base mínima de dados`;q('readinessGrid').innerHTML=checks.map(x=>`<div class="readyItem"><b><span class="readyDot ${x.ok?'ok':'bad'}"></span>${esc(x.name)}</b><small>${esc(x.detail)}</small></div>`).join('');const active=(state.predictions||[]).filter(x=>x.status==='active'&&x.predicted_value!=null);q('predictionStatus').textContent=active.length?'Existem previsões persistidas; cada uma deve ser lida junto de evidência, intervalo e limitações registradas.':`Previsões quantitativas permanecem retidas. ${checks.filter(x=>!x.ok).map(x=>x.name).join(', ')} ainda não têm base mínima de dados.`}
function renderInbox(uploads,previews,req,quality){const previewBy={};previews.forEach(x=>previewBy[x.upload_id]=x);q('uploadList').innerHTML=uploads.length?uploads.map(x=>{const v=previewBy[x.id],range=v?.date_min||v?.date_max?`${fmtDate(v.date_min)} → ${fmtDate(v.date_max)}`:'',schema=v?.detected_schema||'',count=v?.row_count!=null?`${v.row_count} linhas/registros`:'';return `<div class="row"><div><b>${esc(x.original_filename)}</b><small>${esc(x.source_type)} · ${new Date(x.created_at).toLocaleString('pt-BR')}${v?' · '+esc(v.detected_format):''}</small><span class="sourceTag">${esc([schema,count,range].filter(Boolean).join(' · '))}</span></div><span class="pill ${statusPill(x.status)}">${esc(x.status||'uploaded')}</span></div>`}).join(''):empty('Nenhum arquivo enviado ainda.');const completed=req.filter(x=>x.status==='completed').length,total=req.length,cov=total?Math.round(completed/total*100):0;q('coverageBar').style.width=cov+'%';q('coverageLabel').textContent=`${completed}/${total} solicitações concluídas · ${total-completed} pendentes.`;q('requestList').innerHTML=req.length?req.map(x=>`<div class="row"><div><b>${esc(x.source_name||x.domain)}</b><small>${esc(x.notes||'')}</small></div><span class="pill ${statusPill(x.status)}">${esc(x.status||'needed')}</span></div>`).join(''):empty();q('qualityList').innerHTML=quality.length?quality.map(x=>`<div class="row ${x.status==='open'?'qualityOpen':'qualityResolved'}"><div><b>${esc(x.issue_code)} · ${esc(x.category)}</b><small>${esc(x.description)}</small>${x.resolution_notes?`<span class="sourceTag">resolução/nota: ${esc(x.resolution_notes)}</span>`:''}</div><span class="pill ${statusPill(x.status)}">${esc(x.status)}</span></div>`).join(''):empty('Sem registros de auditoria.')}

sb.auth.onAuthStateChange((_event,session)=>setView(session));
(async()=>{const {data:{session}}=await sb.auth.getSession();setView(session)})();
