'use strict';
const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const base='releases/v242/',current='releases/v244/';
const digest=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const previous=JSON.parse(fs.readFileSync(base+'manifest.json'));
for(const [file,hash] of Object.entries(previous.files))assert.equal(digest(base+file),hash,'frozen V242 '+file);
for(const [file,hash] of Object.entries(previous.protected))assert.equal(digest(file),hash,'historical protection '+file);
assert.equal(digest(current+'index.html'),digest(base+'index.html'),'base program must not be rewritten');
const ro=fs.readFileSync('backend/patches/read_only_memo_v244.sql','utf8');
assert.equal((ro.match(/IF NOT current_setting\('transaction_read_only'\)::boolean THEN/g)||[]).length,4);
assert.equal((ro.match(/CREATE OR REPLACE FUNCTION/g)||[]).length,4);
assert(!/\bGRANT\s+(?:EXECUTE|ALL|SELECT)|DROP TABLE|TRUNCATE|DELETE FROM/i.test(ro));
const fgts=fs.readFileSync('backend/patches/historical_fgts_precedence_v244.sql','utf8');
assert.match(fgts,/asset_type='FGTS' AND as_of_date<=dt/);
assert.match(fgts,/WHERE user_id=p_user_id/);
assert.match(fgts,/CASE WHEN position\.value_brl IS NOT NULL/);
assert.match(fgts,/v244\.1:/);
assert(!/GRANT|INSERT INTO public\.asset_positions|UPDATE public\.financial|DELETE FROM/i.test(fgts));
const transport=fs.readFileSync(current+'lts-v227-read-transport.js','utf8');
assert.match(transport,/readBudget=name=>\/\^lts_browser_flow_v\/\.test\(name\)\?48000:25000/);
const chart=fs.readFileSync(current+'lts-v183-v168-feedback-safe.js','utf8');
assert.match(chart,/data-v244-axis-date/);assert.match(chart,/data-v244-rows/);assert.match(chart,/Use as setas para consultar os saldos/);
assert(!/Math\.max\(0,r\.fgts\)/.test(chart),'negative data cannot be visually removed');
console.log('PASS V244 read-only cache guards, dated FGTS precedence, preserved frozen program and complete daily chart');
