'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
require('./lts_v246_source_gate.js');
const read=n=>fs.readFileSync('backend/patches/'+n,'utf8');
const cash=read('corrected_cash_memo_v247.sql');
assert.match(cash,/c.from_date=p_from AND c.to_date=p_to/);
assert.match(cash,/current_setting\('TimeZone'\)/);
assert.match(cash,/America\/Sao_Paulo/);
assert.match(cash,/source_epoch IS DISTINCT FROM/);
assert.match(cash,/ORDER BY a.ord/);
assert.match(cash,/REVOKE ALL ON FUNCTION public\.lts_corrected_cashflow_fix86_v1_engine_v247\(uuid,date,date\) FROM PUBLIC,anon,authenticated/);
const safety=read('read_only_memo_safety_v247.sql');
assert.match(safety,/EXCEPTION WHEN read_only_sql_transaction THEN NULL/);
assert(!/WHEN OTHERS|insufficient_privilege|42501/i.test(safety));
assert(!/transaction_read_only\s*=\s*['"]?off|DISABLE TRIGGER|DROP POLICY|GRANT.*authenticated/i.test(cash+safety));
assert.match(safety,/ALTER FUNCTION public\.lts_dashboard_source_key_v240\(uuid\) VOLATILE/);
const dependencies=read('documentary_cache_dependencies_v247.sql');
const future=read('read_only_future_fallback_v247.sql');
assert.match(future,/if current_setting\('transaction_read_only'\)::boolean then/);
assert.match(future,/public\.lts_daily_flow_fix86_v20\(p_user_id,current_date,horizon_end\)/);
assert.match(future,/coalesce\(\(select to_date-current_date/);
assert.match(future,/REVOKE ALL ON FUNCTION public\.lts_flow_future_read_slice_v9_pre_v247\(uuid,date,date\) FROM PUBLIC,anon,authenticated/);
assert(!/WHEN OTHERS|insufficient_privilege|default_transaction_read_only\s*=.*off/i.test(future));
for(const table of ['lts_card_document_supplement_v234','lts_card_history_source_audit_v235'])assert(dependencies.includes(table));
for(const action of ['INSERT','UPDATE','DELETE','TRUNCATE'])assert(dependencies.includes('AFTER '+action));
const qa=fs.readFileSync('backend/qa/lts_v247_cash_rollback.sql','utf8');
assert.match(qa,/EXCEPTION WHEN SQLSTATE 'P2470'/);
assert.match(qa,/ROLLBACK;/);assert(!/COMMIT;/i.test(qa));
console.log('PASS V247 exact cash memo, read-only safety, documentary invalidation and preserved V245');
